---
title: "Differential abundance analysis"
author: Cas Swarte
output: html_notebook
# ==========================================================================================
#                       By: Weersma Group, TransplantLines (UMCG)
#
#                       UMCG Transplantlines Project data analysis
# ==========================================================================================
#
#                           Differential abundance analysis 
#         (Liver Transplant Recipients [LTR], Renal Transplant Recipients [RTR])
#           (End-stage liver disease [ESLD], End-stage renal disease [ESRD])
#                  
# ==========================================================================================
#
# NOTE: This is implementation on Mock Data published in this github repo, and is intended 
# for demonstration purposes only, the results are not identical to Figures in the manuscript
#
# NOTE2: Codes are intended to be run from root of this github repo, if running them from 
# different location, make sure to adjust setwd to appropriate location 
# (root of this github repo)
#
# ==========================================================================================
#
# make sure following packages are installed:
# install.packages(c('foreign','tidyverse','ggsignif','survival','rms','survminer'))
#
# ==========================================================================================
---


```{r}
#Load packages
library(foreign)
library(stringr)
library(tidyverse)
library(ggrepel)
library(ggpubr)
library(scales)
library(gsubfn)
library(xlsx)
library(ggcorrplot)
```
```{r}
#Load Data ----
#Taxa - Filtered MetaPhlAn2 output
CDtaxa <- read.csv("mock_data/deicode_input/Mocks_Taxa_Filtered.csv", row.names=1)
CDtaxa <- t.data.frame(CDtaxa)
CDtaxa <- as.data.frame(CDtaxa)
CDtaxa$ID <- row.names(CDtaxa)
CDtaxa$ID <- gsub("MOCK_","",CDtaxa$ID)

  
#Pathways - Filtered HUMAnN2 output
CDpwys <- read.csv("mock_data/deicode_input/Mocks_Pathways_Filtered.csv", row.names=1)
CDpwys <- t.data.frame(CDpwys)
CDpwys <- as.data.frame(CDpwys)
CDpwys$ID <- row.names(CDpwys)
CDpwys$ID <- gsub("MOCK_","",CDpwys$ID)

#Antibiotic Res. Genes - Filtered CARD output
CDcard <- read.csv("mock_data/deicode_input/Mocks_CARD_Filtered.csv", row.names=1)
CDcard <- t.data.frame(CDcard)
CDcard <- as.data.frame(CDcard)
CDcard$ID <- row.names(CDcard)
CDcard$ID <- gsub("MOCK_","",CDcard$ID)

#Virulence Factors - Filtered VFDB output
CDvfdb <- read.csv("mock_data/deicode_input/Mocks_CARD_Filtered.csv", row.names=1)
CDvfdb <- t.data.frame(CDvfdb)
CDvfdb <- as.data.frame(CDvfdb)
CDvfdb$ID <- row.names(CDvfdb)
CDvfdb$ID <- gsub("MOCK_","",CDvfdb$ID)

#Metadata
CDmeta <- read.csv("mock_data/Mock_Meta_Final.csv", row.names=1)
CDmeta$ID <- row.names(CDmeta)
CDmeta$ID <- trimws(CDmeta$ID)
row.names(CDmeta) <- CDmeta$ID
CDmeta_All <- subset(CDmeta, Cross_sectional_samples == "LTR" | Cross_sectional_samples == "RTR" | Cross_sectional_samples == "Healthy Control" )

#Selecting cross-sectional samples
#Taxa
CDtaxa_All <- CDmeta_All["ID"]
CDtaxa_All <- merge(CDtaxa_All, CDtaxa, by="ID")
row.names(CDtaxa_All) <- CDtaxa_All$ID
CDtaxa_All$ID <- NULL
#Pathways
CDpwys_All <- CDmeta_All["ID"]
CDpwys_All <- merge(CDpwys_All, CDpwys, by="ID")
row.names(CDpwys_All) <- CDpwys_All$ID
CDpwys_All$ID <- NULL
#Antibiotic Res. Genes
CDcard_All <- CDmeta_All["ID"]
CDcard_All <- merge(CDcard_All, CDcard, by="ID")
row.names(CDcard_All) <- CDcard_All$ID
CDcard_All$ID <- NULL
CDcard_All <- CDcard_All[!is.na(rowSums(CDcard_All)),]
#Virulence Factors
CDvfdb_All <- CDmeta_All["ID"]
CDvfdb_All <- merge(CDvfdb_All, CDvfdb, by="ID")
row.names(CDvfdb_All) <- CDvfdb_All$ID
CDvfdb_All$ID <- NULL

# this is the RCLR transformed data from deicode
#Taxa - DEICODE output
ftbl_rclr_species <- read.csv("mock_data/deicode_output/Mocks_Taxa_Filtered_rclr.csv", row.names=1)

CDtaxa_All_only_s <-  CDtaxa_All[,grep(x=colnames(CDtaxa_All),pattern="s__")]
row.names(CDtaxa_All_only_s)
rownames(ftbl_rclr_species) <- str_split_fixed(colnames(CDtaxa_All_only_s), "\\.", 7)[,7] #colnames(CDtaxa_All_only_s)
colnames(ftbl_rclr_species) <- rownames(CDtaxa_All_only_s)

#Pathways - DEICODE output
ftbl_rclr_pwys <- 
  read.csv("mock_data/deicode_output/Mocks_Pathways_Filtered_rclr.csv", row.names=1)
rownames(ftbl_rclr_pwys) <- colnames(CDpwys_All)
colnames(ftbl_rclr_pwys) <- rownames(CDpwys_All)

#Antibiotic Res. Genes - DEICODE output
ftbl_rclr_card <- 
  read.csv("mock_data/deicode_output/Mocks_CARD_Filtered_rclr.csv", row.names=1)
rownames(ftbl_rclr_card) <- colnames(CDcard_All)
colnames(ftbl_rclr_card) <- rownames(CDcard_All)

#Virulence Factors - DEICODE output
ftbl_rclr_vfdb <- 
  read.csv("mock_data/deicode_output/Mocks_VF_Filtered_rclr.csv", row.names=1)
rownames(ftbl_rclr_vfdb) <- colnames(CDvfdb_All)
colnames(ftbl_rclr_vfdb) <- rownames(CDvfdb_All)
colnames(ftbl_rclr_vfdb) <- gsub("MOCK_","", colnames(ftbl_rclr_vfdb))
```
```{r}
#3.2      DA LM for Taxa and Pathways LTR vs HC----
meta_liver <- CDmeta_All %>%
  select(ID, Cross_sectional_samples, Age, BMI, Gender, Smoking, PPI, Laxative, Antibiotics) %>%
  filter(Cross_sectional_samples %in% c("Healthy Control","LTR")) %>%
  mutate(Group=relevel(factor(Cross_sectional_samples), ref="Healthy Control")) %>%
  select(-Cross_sectional_samples)

# subset abundance table to focal samples
ftbl_rclr <- ftbl_rclr_species[,colnames(ftbl_rclr_species) %in% meta_liver$ID]
ftbl_rclr <- t(ftbl_rclr)
ftbl_rclr_df <- data.frame(ftbl_rclr)
# Species - Taxon-specific linear models 
lm_data <- 
  lm_data <- data.frame(ftbl_rclr) %>%
  rownames_to_column("ID") %>%
  left_join(meta_liver, by="ID")

lm_ls <- vector("list", ncol(ftbl_rclr))
names(lm_ls) <- colnames(ftbl_rclr)
for(taxon in colnames(ftbl_rclr)) {
  tryCatch({
    print(taxon)
    m <- lm(lm_data[,taxon] ~ Group + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics, data=lm_data[,c(taxon,"Group", "Age", "BMI", "Gender", "Smoking", "PPI", "Laxative", "Antibiotics")])
    
    mm <- coef(summary(m))[2,c(1,2,4)]
    names(mm)[3] <- "p_val"
    lm_ls[[taxon]] <- mm
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}

# ERROR : contrasts can be applied only to factors with 2 or more levels
# This is caused by to few samples in e.g. Smoking variable
lm_ls[sapply(lm_ls, is.null)] <- NULL

#FDR correction
lm_df <- lm_ls %>%
  bind_rows(.id="taxon_id") %>%
  mutate(p_adj=p.adjust(p_val, "BH"))
lm_df

#Pathways
meta_liver <- CDmeta_All %>%
  select(ID, Cross_sectional_samples, Age, BMI, Gender, Smoking, PPI, Laxative, Antibiotics) %>%
  filter(Cross_sectional_samples %in% c("Healthy Control","LTR")) %>%
  mutate(Group=relevel(factor(Cross_sectional_samples), ref="Healthy Control")) %>%
  select(-Cross_sectional_samples)

# subset abundance table to focal samples
ftbl_rclr <- ftbl_rclr_pwys[,colnames(ftbl_rclr_pwys) %in% meta_liver$ID] 
ftbl_rclr <- t(ftbl_rclr)

# Species - Taxon-specific linear models 

lm_data <- #
  lm_data <- data.frame(ftbl_rclr) %>%
  rownames_to_column("ID") %>%
  left_join(meta_liver, by="ID")

lm_ls <- vector("list", ncol(ftbl_rclr))
names(lm_ls) <- colnames(ftbl_rclr)
for(taxon in colnames(ftbl_rclr)) {
  tryCatch({
    print(taxon)
    m <- lm(lm_data[,taxon] ~ Group + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics, data=lm_data[,c(taxon,"Group", "Age", "BMI", "Gender", "Smoking", "PPI", "Laxative", "Antibiotics")])
    
    mm <- coef(summary(m))[2,c(1,2,4)]
    names(mm)[3] <- "p_val"
    
    lm_ls[[taxon]] <- mm
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}

# ERROR : contrasts can be applied only to factors with 2 or more levels
# This is caused by to few samples in e.g. Smoking variable
lm_ls[sapply(lm_ls, is.null)] <- NULL

#FDR correction
lm_df <- lm_ls %>%
  bind_rows(.id="taxon_id") %>%
  mutate(p_adj=p.adjust(p_val, "BH"))
lm_df
```
```{r}
#3.3      DA LTR vs HC CARD VFDB PA----
#CARD
meta_liver <- CDmeta_All %>%
  select(ID, Cross_sectional_samples, Age, BMI, Gender, Smoking, PPI, Laxative, Antibiotics) %>%
  filter(Cross_sectional_samples %in% c("Healthy Control","LTR")) %>%
  mutate(Group=relevel(factor(Cross_sectional_samples), ref="Healthy Control")) %>%
  select(-Cross_sectional_samples)
summary(meta_liver$Group)
# subset abundance table to focal samples
ftbl_rclr <- ftbl_rclr_card[,colnames(ftbl_rclr_card) %in% meta_liver$ID] 
ftbl_rclr <- t(ftbl_rclr)
ftbl_rclr_PA <- data.frame(ftbl_rclr)

for (cn in colnames(ftbl_rclr_PA)) {
  ftbl_rclr_PA[[cn]][ftbl_rclr_PA[[cn]] > 0] <- 1
  ftbl_rclr_PA[[cn]][ftbl_rclr_PA[[cn]] <= 0] <- 1
}
ftbl_rclr_PA[is.na(ftbl_rclr_PA)] <- 0

ftbl_rclr_PA <- ftbl_rclr_PA[,colSums(ftbl_rclr_PA)>0]

glm_data <- 
  glm_data <- data.frame(ftbl_rclr_PA) %>%
  rownames_to_column("ID") %>%
  left_join(meta_liver, by="ID")

lm_ls <- vector("list", ncol(ftbl_rclr_PA))
names(lm_ls) <- colnames(ftbl_rclr_PA)
for(taxon in colnames(ftbl_rclr_PA)) {
  tryCatch({
    print(taxon)
    m <- glm(glm_data[,taxon] ~ Group + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics, data=glm_data[,c(taxon,"Group", "Age", "BMI", "Gender", "Smoking", "PPI", "Laxative", "Antibiotics")], family = binomial)
    mm <- coef(summary(m))[2,c(1,2,4)]
    names(mm)[3] <- "p_val"
    a <- tapply(glm_data[,taxon], glm_data$Group, sum)
    mm[4] <- a[1]
    names(mm)[4] <- paste0("n_", names(a)[1])
    mm[5] <- a[1] / summary(glm_data$Group)[1]
    names(mm)[5] <- paste0("%_", names(a)[1])
    mm[6] <- a[2] 
    names(mm)[6] <- paste0("n_", names(a)[2])
    mm[7] <- a[2] / summary(glm_data$Group)[2]
    names(mm)[7] <- paste0("%_", names(a)[2])
    lm_ls[[taxon]] <- mm
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}

# ERROR : contrasts can be applied only to factors with 2 or more levels
# This is caused by to few samples in e.g. Smoking variable
lm_ls[sapply(lm_ls, is.null)] <- NULL

#FDR correction
lm_df <- lm_ls %>%
  bind_rows(.id="taxon_id") %>%
  mutate(p_adj=p.adjust(p_val, "BH"))

dat <- lm_df %>%
  mutate(sign=sign(Estimate),
         Direction=ifelse(sign=="1","Increased","Decreased"),
         p_adj_sig=ifelse(p_adj<0.1, "Yes", "No"),
         taxon_id=fct_reorder(taxon_id, Estimate, median))
dat$sign <- NULL
dat

#Filter on prevalence here
lm_df_filter01 <- dat %>% 
  filter(`%_LTR`>0.1 & `%_Healthy Control`>0.1)
lm_df_filter01

lm_df_filter001 <- dat %>% 
  filter(`%_LTR`>0.01 & `%_Healthy Control`>0.01)
lm_df_filter001

#VFDB
meta_liver <- CDmeta_All %>%
  select(ID, Cross_sectional_samples, Age, BMI, Gender, Smoking, PPI, Laxative, Antibiotics) %>%
  filter(Cross_sectional_samples %in% c("Healthy Control","LTR")) %>%
  mutate(Group=relevel(factor(Cross_sectional_samples), ref="Healthy Control")) %>%
  select(-Cross_sectional_samples)
summary(meta_liver$Group)
# subset abundance table to focal samples
ftbl_rclr <- ftbl_rclr_vfdb[,colnames(ftbl_rclr_vfdb) %in% meta_liver$ID] 
ftbl_rclr <- t(ftbl_rclr)
ftbl_rclr_PA <- data.frame(ftbl_rclr)

for (cn in colnames(ftbl_rclr_PA)) {
  ftbl_rclr_PA[[cn]][ftbl_rclr_PA[[cn]] > 0] <- 1
  ftbl_rclr_PA[[cn]][ftbl_rclr_PA[[cn]] <= 0] <- 1
}
ftbl_rclr_PA[is.na(ftbl_rclr_PA)] <- 0
ftbl_rclr_PA <- ftbl_rclr_PA[,colSums(ftbl_rclr_PA)>0]

glm_data <- #
  glm_data <- data.frame(ftbl_rclr_PA) %>%
  rownames_to_column("ID") %>%
  left_join(meta_liver, by="ID")

lm_ls <- vector("list", ncol(ftbl_rclr_PA))
names(lm_ls) <- colnames(ftbl_rclr_PA)
for(taxon in colnames(ftbl_rclr_PA)) {
  tryCatch({
    print(taxon)
    m <- glm(glm_data[,taxon] ~ Group + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics, data=glm_data[,c(taxon,"Group", "Age", "BMI", "Gender", "Smoking", "PPI", "Laxative", "Antibiotics")], family = binomial)
    mm <- coef(summary(m))[2,c(1,2,4)]
    names(mm)[3] <- "p_val"
    a <- tapply(glm_data[,taxon], glm_data$Group, sum)
    
    mm[4] <- a[1]
    names(mm)[4] <- paste0("n_", names(a)[1])
    mm[5] <- a[1] / summary(glm_data$Group)[1]
    names(mm)[5] <- paste0("%_", names(a)[1])
    mm[6] <- a[2] 
    names(mm)[6] <- paste0("n_", names(a)[2])
    mm[7] <- a[2] / summary(glm_data$Group)[2]
    names(mm)[7] <- paste0("%_", names(a)[2])
    lm_ls[[taxon]] <- mm
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}

# ERROR : contrasts can be applied only to factors with 2 or more levels
# This is caused by to few samples in e.g. Smoking variable
lm_ls[sapply(lm_ls, is.null)] <- NULL

#FDR correction
lm_df <- lm_ls %>%
  bind_rows(.id="taxon_id") %>%
  mutate(p_adj=p.adjust(p_val, "BH"))

#lm_df[lm_df$taxon_id=="gb.AAG03357_1.ARO_3000596.ErmX__Corynebacterium_striatum_",]

dat <- lm_df %>%
  mutate(sign=sign(Estimate),
         Direction=ifelse(sign=="1","Increased","Decreased"),
         p_adj_sig=ifelse(p_adj<0.1, "Yes", "No"),
         taxon_id=fct_reorder(taxon_id, Estimate, median))
dat$sign <- NULL
dat

#Filter on prevalence here
lm_df_filter01 <- dat %>% 
  filter(`%_LTR`>0.1 & `%_Healthy Control`>0.1)
lm_df_filter01
lm_df_filter001 <- dat %>% 
  filter(`%_LTR`>0.01 & `%_Healthy Control`>0.01)
lm_df_filter001
```
```{r}
#3.4      DA RTR LM for Taxa and Pathways vs HC----
meta_renal <- CDmeta_All %>%
  select(ID, Cross_sectional_samples, Age, BMI, Gender, Smoking, PPI, Laxative, Antibiotics) %>%
  filter(Cross_sectional_samples %in% c("Healthy Control","RTR")) %>%
  mutate(Group=relevel(factor(Cross_sectional_samples), ref="Healthy Control")) %>%
  select(-Cross_sectional_samples)

# subset abundance table to focal samples
ftbl_rclr <- ftbl_rclr_species[,colnames(ftbl_rclr_species) %in% meta_renal$ID] 
ftbl_rclr <- t(ftbl_rclr)
ftbl_rclr_df <- data.frame(ftbl_rclr)
# Species - Taxon-specific linear models 

lm_data <- #
  lm_data <- data.frame(ftbl_rclr) %>%
  rownames_to_column("ID") %>%
  left_join(meta_renal, by="ID")

lm_ls <- vector("list", ncol(ftbl_rclr))
names(lm_ls) <- colnames(ftbl_rclr)
for(taxon in colnames(ftbl_rclr)) {
  tryCatch({
    print(taxon)
    m <- lm(lm_data[,taxon] ~ Group + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics, data=lm_data[,c(taxon,"Group", "Age", "BMI", "Gender", "Smoking", "PPI", "Laxative", "Antibiotics")])
    
    mm <- coef(summary(m))[2,c(1,2,4)]
    names(mm)[3] <- "p_val"
    
    lm_ls[[taxon]] <- mm
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}

# ERROR : contrasts can be applied only to factors with 2 or more levels
# This is caused by to few samples in e.g. Smoking variable
lm_ls[sapply(lm_ls, is.null)] <- NULL

#FDR correction
lm_df <- lm_ls %>%
  bind_rows(.id="taxon_id") %>%
  mutate(p_adj=p.adjust(p_val, "BH"))

dat <- lm_df %>%
  mutate(sign=sign(Estimate),
         Direction=ifelse(sign=="1","Increased","Decreased"),
         p_adj_sig=ifelse(p_adj<0.1, "Yes", "No"),
         taxon_id=fct_reorder(taxon_id, Estimate, median)) 
dat$sign <- NULL
dat %>%
  filter(p_adj_sig=="Yes")

#Pathways
meta_renal <- CDmeta_All %>%
  select(ID, Cross_sectional_samples, Age, BMI, Gender, Smoking, PPI, Laxative, Antibiotics) %>%
  filter(Cross_sectional_samples %in% c("Healthy Control","RTR")) %>%
  mutate(Group=relevel(factor(Cross_sectional_samples), ref="Healthy Control")) %>%
  select(-Cross_sectional_samples)
meta_renal[is.na(meta_renal$Smoking),]$Smoking <- "Nee"

# subset abundance table to focal samples
ftbl_rclr <- ftbl_rclr_pwys[,colnames(ftbl_rclr_pwys) %in% meta_renal$ID] 
ftbl_rclr <- t(ftbl_rclr)

# Species - Taxon-specific linear models 
lm_data <- #
  lm_data <- data.frame(ftbl_rclr) %>%
  rownames_to_column("ID") %>%
  left_join(meta_renal, by="ID")

lm_ls <- vector("list", ncol(ftbl_rclr))
names(lm_ls) <- colnames(ftbl_rclr)
for(taxon in colnames(ftbl_rclr)) {
  tryCatch({
    print(taxon)
    m <- lm(lm_data[,taxon] ~ Group + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics, data=lm_data[,c(taxon,"Group", "Age", "BMI", "Gender", "Smoking", "PPI", "Laxative", "Antibiotics")])
    
    mm <- coef(summary(m))[2,c(1,2,4)]
    names(mm)[3] <- "p_val"
    
    lm_ls[[taxon]] <- mm
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}

# ERROR : contrasts can be applied only to factors with 2 or more levels
# This is caused by to few samples in e.g. Smoking variable
lm_ls[sapply(lm_ls, is.null)] <- NULL

#FDR correction
lm_df <- lm_ls %>%
  bind_rows(.id="taxon_id") %>%
  mutate(p_adj=p.adjust(p_val, "BH"))

dat <- lm_df %>%
  mutate(sign=sign(Estimate),
         Direction=ifelse(sign=="1","Increased","Decreased"),
         p_adj_sig=ifelse(p_adj<0.1, "Yes", "No"),
         taxon_id=fct_reorder(taxon_id, Estimate, median))
dat$sign <- NULL
dat %>%
  filter(p_adj_sig=="Yes")
```
```{r}
#3.5      DA RTR vs HC CARD VFDB PA----
#CARD
meta_renal <- CDmeta_All %>%
  select(ID, Cross_sectional_samples, Age, BMI, Gender, Smoking, PPI, Laxative, Antibiotics) %>%
  filter(Cross_sectional_samples %in% c("Healthy Control","RTR")) %>%
  mutate(Group=relevel(factor(Cross_sectional_samples), ref="Healthy Control")) %>%
  select(-Cross_sectional_samples)
summary(meta_renal$Group)
# subset abundance table to focal samples
ftbl_rclr <- ftbl_rclr_card[,colnames(ftbl_rclr_card) %in% meta_renal$ID] 
ftbl_rclr <- t(ftbl_rclr)
ftbl_rclr_PA <- data.frame(ftbl_rclr)

for (cn in colnames(ftbl_rclr_PA)) {
  ftbl_rclr_PA[[cn]][ftbl_rclr_PA[[cn]] > 0] <- 1
  ftbl_rclr_PA[[cn]][ftbl_rclr_PA[[cn]] <= 0] <- 1
}
ftbl_rclr_PA[is.na(ftbl_rclr_PA)] <- 0
ftbl_rclr_PA <- ftbl_rclr_PA[,colSums(ftbl_rclr_PA)>0]

glm_data <- #
  glm_data <- data.frame(ftbl_rclr_PA) %>%
  rownames_to_column("ID") %>%
  left_join(meta_renal, by="ID")

lm_ls <- vector("list", ncol(ftbl_rclr_PA))
names(lm_ls) <- colnames(ftbl_rclr_PA)
for(taxon in colnames(ftbl_rclr_PA)) {
  tryCatch({
    print(taxon)
    m <- glm(glm_data[,taxon] ~ Group + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics, data=glm_data[,c(taxon,"Group", "Age", "BMI", "Gender", "Smoking", "PPI", "Laxative", "Antibiotics")], family = binomial)
    mm <- coef(summary(m))[2,c(1,2,4)]
    names(mm)[3] <- "p_val"
    a <- tapply(glm_data[,taxon], glm_data$Group, sum)
    
    mm[4] <- a[1]
    names(mm)[4] <- paste0("n_", names(a)[1])
    mm[5] <- a[1] / summary(glm_data$Group)[1]
    names(mm)[5] <- paste0("%_", names(a)[1])
    mm[6] <- a[2] 
    names(mm)[6] <- paste0("n_", names(a)[2])
    mm[7] <- a[2] / summary(glm_data$Group)[2]
    names(mm)[7] <- paste0("%_", names(a)[2])
    lm_ls[[taxon]] <- mm
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}

# ERROR : contrasts can be applied only to factors with 2 or more levels
# This is caused by to few samples in e.g. Smoking variable
lm_ls[sapply(lm_ls, is.null)] <- NULL

#FDR correction
lm_df <- lm_ls %>%
  bind_rows(.id="taxon_id") %>%
  mutate(p_adj=p.adjust(p_val, "BH"))

dat <- lm_df %>%
  mutate(sign=sign(Estimate),
         Direction=ifelse(sign=="1","Increased","Decreased"),
         p_adj_sig=ifelse(p_adj<0.1, "Yes", "No"),
         taxon_id=fct_reorder(taxon_id, Estimate, median))
dat$sign <- NULL
dat
dat %>%
  filter(p_adj_sig=="Yes")

#Filter on prevalence here
lm_df_filter01 <- dat %>% 
  filter(`%_RTR`>0.1 & `%_Healthy Control`>0.1)
lm_df_filter01
lm_df_filter001 <- dat %>% 
  filter(`%_RTR`>0.01 & `%_Healthy Control`>0.01)
lm_df_filter001

#VFDB
meta_renal <- CDmeta_All %>%
  select(ID, Cross_sectional_samples, Age, BMI, Gender, Smoking, PPI, Laxative, Antibiotics) %>%
  filter(Cross_sectional_samples %in% c("Healthy Control","RTR")) %>%
  mutate(Group=relevel(factor(Cross_sectional_samples), ref="Healthy Control")) %>%
  select(-Cross_sectional_samples)
summary(meta_renal$Group)
# subset abundance table to focal samples
ftbl_rclr <- ftbl_rclr_vfdb[,colnames(ftbl_rclr_vfdb) %in% meta_renal$ID] 
ftbl_rclr <- t(ftbl_rclr)
ftbl_rclr_PA <- data.frame(ftbl_rclr)

for (cn in colnames(ftbl_rclr_PA)) {
  ftbl_rclr_PA[[cn]][ftbl_rclr_PA[[cn]] > 0] <- 1
  ftbl_rclr_PA[[cn]][ftbl_rclr_PA[[cn]] <= 0] <- 1
}
ftbl_rclr_PA[is.na(ftbl_rclr_PA)] <- 0
ftbl_rclr_PA <- ftbl_rclr_PA[,colSums(ftbl_rclr_PA)>0]
# Species - Taxon-specific linear models 
# use meta_renal or meta_renal
glm_data <- #
  glm_data <- data.frame(ftbl_rclr_PA) %>%
  rownames_to_column("ID") %>%
  left_join(meta_renal, by="ID")

lm_ls <- vector("list", ncol(ftbl_rclr_PA))
names(lm_ls) <- colnames(ftbl_rclr_PA)
for(taxon in colnames(ftbl_rclr_PA)) {
  tryCatch({
    print(taxon)
    m <- glm(glm_data[,taxon] ~ Group + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics, data=glm_data[,c(taxon,"Group", "Age", "BMI", "Gender", "Smoking", "PPI", "Laxative", "Antibiotics")], family = binomial)
    mm <- coef(summary(m))[2,c(1,2,4)]
    names(mm)[3] <- "p_val"
    a <- tapply(glm_data[,taxon], glm_data$Group, sum)
    
    mm[4] <- a[1]
    names(mm)[4] <- paste0("n_", names(a)[1])
    mm[5] <- a[1] / summary(glm_data$Group)[1]
    names(mm)[5] <- paste0("%_", names(a)[1])
    mm[6] <- a[2] 
    names(mm)[6] <- paste0("n_", names(a)[2])
    mm[7] <- a[2] / summary(glm_data$Group)[2]
    names(mm)[7] <- paste0("%_", names(a)[2])
    lm_ls[[taxon]] <- mm
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}

# ERROR : contrasts can be applied only to factors with 2 or more levels
# This is caused by to few samples in e.g. Smoking variable
lm_ls[sapply(lm_ls, is.null)] <- NULL

#FDR correction
lm_df <- lm_ls %>%
  bind_rows(.id="taxon_id") %>%
  mutate(p_adj=p.adjust(p_val, "BH"))

dat <- lm_df %>%
  mutate(sign=sign(Estimate),
         Direction=ifelse(sign=="1","Increased","Decreased"),
         p_adj_sig=ifelse(p_adj<0.1, "Yes", "No"),
         taxon_id=fct_reorder(taxon_id, Estimate, median))
dat$sign <- NULL
dat %>%
  filter(p_adj_sig=="Yes")

#Filter on prevalence here
lm_df_filter01 <- dat %>% 
  filter(`%_RTR`>0.1 & `%_Healthy Control`>0.1)
lm_df_filter01
lm_df_filter001 <- dat %>% 
  filter(`%_RTR`>0.01 & `%_Healthy Control`>0.01)
lm_df_filter001
```
```{r}
#3.6      DA ESLD vs HC----
meta_liver <- CDmeta %>%
  select(ID, Timepoint_All, Age, BMI, Gender, Smoking, PPI, Laxative, Antibiotics) %>%
  filter(Timepoint_All %in% c("Healthy Control","PreTxLTR_TxL")) %>%
  mutate(Group=relevel(factor(Timepoint_All), ref="Healthy Control")) %>%
  select(-Timepoint_All)

# subset abundance table to focal samples
ftbl_rclr <- ftbl_rclr_species[,colnames(ftbl_rclr_species) %in% meta_liver$ID] 
ftbl_rclr <- t(ftbl_rclr)

# Species - Taxon-specific linear models 

lm_data <- #
  lm_data <- data.frame(ftbl_rclr) %>%
  rownames_to_column("ID") %>%
  left_join(meta_liver, by="ID")

lm_ls <- vector("list", ncol(ftbl_rclr))
names(lm_ls) <- colnames(ftbl_rclr)
for(taxon in colnames(ftbl_rclr)) {
  tryCatch({
    print(taxon)
    m <- lm(lm_data[,taxon] ~ Group + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics, data=lm_data[,c(taxon,"Group", "Age", "BMI", "Gender", "Smoking", "PPI", "Laxative", "Antibiotics")])
    
    mm <- coef(summary(m))[2,c(1,2,4)]
    names(mm)[3] <- "p_val"
    
    lm_ls[[taxon]] <- mm
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}

# ERROR : contrasts can be applied only to factors with 2 or more levels
# This is caused by to few samples in e.g. Smoking variable
lm_ls[sapply(lm_ls, is.null)] <- NULL

#FDR correction
lm_df <- lm_ls %>%
  bind_rows(.id="taxon_id") %>%
  mutate(p_adj=p.adjust(p_val, "BH"))

dat <- lm_df %>%
  mutate(sign=sign(Estimate),
         Direction=ifelse(sign=="1","Increased","Decreased"),
         p_adj_sig=ifelse(p_adj<0.1, "Yes", "No"),
         taxon_id=fct_reorder(taxon_id, Estimate, median)) 
dat

#Pathways
meta_liver <- CDmeta %>%
  select(ID, Timepoint_All, Age, BMI, Gender, Smoking, PPI, Laxative, Antibiotics) %>%
  filter(Timepoint_All %in% c("Healthy Control","PreTxLTR_TxL")) %>%
  mutate(Group=relevel(factor(Timepoint_All), ref="Healthy Control")) %>%
  select(-Timepoint_All)

# subset abundance table to focal samples
ftbl_rclr <- ftbl_rclr_pwys[,colnames(ftbl_rclr_pwys) %in% meta_liver$ID] 
ftbl_rclr <- t(ftbl_rclr)

# Species - Taxon-specific linear models 

lm_data <- #
  lm_data <- data.frame(ftbl_rclr) %>%
  rownames_to_column("ID") %>%
  left_join(meta_liver, by="ID")

lm_ls <- vector("list", ncol(ftbl_rclr))
names(lm_ls) <- colnames(ftbl_rclr)
for(taxon in colnames(ftbl_rclr)) {
  tryCatch({
    print(taxon)
    m <- lm(lm_data[,taxon] ~ Group + Age+ BMI + Gender + Smoking + PPI + Laxative + Antibiotics, data=lm_data[,c(taxon,"Group", "Age", "BMI", "Gender", "Smoking", "PPI", "Laxative", "Antibiotics")])
    
    mm <- coef(summary(m))[2,c(1,2,4)]
    names(mm)[3] <- "p_val"
    
    lm_ls[[taxon]] <- mm
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}

# ERROR : contrasts can be applied only to factors with 2 or more levels
# This is caused by to few samples in e.g. Smoking variable
lm_ls[sapply(lm_ls, is.null)] <- NULL

#FDR correction
lm_df <- lm_ls %>%
  bind_rows(.id="taxon_id") %>%
  mutate(p_adj=p.adjust(p_val, "BH"))

dat <- lm_df %>%
  mutate(sign=sign(Estimate),
         Direction=ifelse(sign=="1","Increased","Decreased"),
         p_adj_sig=ifelse(p_adj<0.1, "Yes", "No"),
         taxon_id=fct_reorder(taxon_id, Estimate, median))
dat$sign <- NULL
dat %>%
  filter(p_adj_sig=="Yes")
dat <- dat %>%
  rename(`P-value`=p_val, 
         PFDR = p_adj,
         `Significant (PFDR<0.1)` = p_adj_sig,
         `Standard error` = `Std. Error`)
dat
```
```{r}
#3.7      DA ESLD vs HC CARD VFDB PA----
#CARD
meta_liver <- CDmeta %>%
  select(ID, Timepoint_All, Age, BMI, Gender, Smoking, PPI, Laxative, Antibiotics) %>%
  filter(Timepoint_All %in% c("Healthy Control","PreTxLTR_TxL")) %>%
  mutate(Group=relevel(factor(Timepoint_All), ref="Healthy Control")) %>%
  select(-Timepoint_All)
summary(meta_liver$Group)

# subset abundance table to focal samples
ftbl_rclr <- ftbl_rclr_card[,colnames(ftbl_rclr_card) %in% meta_liver$ID] 
ftbl_rclr <- t(ftbl_rclr)
ftbl_rclr_PA <- data.frame(ftbl_rclr)

for (cn in colnames(ftbl_rclr_PA)) {
  ftbl_rclr_PA[[cn]][ftbl_rclr_PA[[cn]] > 0] <- 1
  ftbl_rclr_PA[[cn]][ftbl_rclr_PA[[cn]] <= 0] <- 1
}
ftbl_rclr_PA[is.na(ftbl_rclr_PA)] <- 0
ftbl_rclr_PA <- ftbl_rclr_PA[,colSums(ftbl_rclr_PA)>0]

glm_data <- #
  glm_data <- data.frame(ftbl_rclr_PA) %>%
  rownames_to_column("ID") %>%
  left_join(meta_liver, by="ID")

lm_ls <- vector("list", ncol(ftbl_rclr_PA))
names(lm_ls) <- colnames(ftbl_rclr_PA)
for(taxon in colnames(ftbl_rclr_PA)) {
  tryCatch({
    print(taxon)
    m <- glm(glm_data[,taxon] ~ Group + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics, data=glm_data[,c(taxon,"Group", "Age", "BMI", "Gender", "Smoking", "PPI", "Laxative", "Antibiotics")], family = binomial)
    mm <- coef(summary(m))[2,c(1,2,4)]
    names(mm)[3] <- "p_val"
    a <- tapply(glm_data[,taxon], glm_data$Group, sum)
    
    mm[4] <- a[1]
    names(mm)[4] <- paste0("n_", names(a)[1])
    mm[5] <- a[1] / summary(glm_data$Group)[1]
    names(mm)[5] <- paste0("%_", names(a)[1])
    mm[6] <- a[2] 
    names(mm)[6] <- paste0("n_", names(a)[2])
    mm[7] <- a[2] / summary(glm_data$Group)[2]
    names(mm)[7] <- paste0("%_", names(a)[2])
    lm_ls[[taxon]] <- mm
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}

# ERROR : contrasts can be applied only to factors with 2 or more levels
# This is caused by to few samples in e.g. Smoking variable
lm_ls[sapply(lm_ls, is.null)] <- NULL

#FDR correction
lm_df <- lm_ls %>%
  bind_rows(.id="taxon_id") %>%
  mutate(p_adj=p.adjust(p_val, "BH"))

dat <- lm_df %>%
  mutate(sign=sign(Estimate),
         Direction=ifelse(sign=="1","Increased","Decreased"),
         p_adj_sig=ifelse(p_adj<0.1, "Yes", "No"),
         taxon_id=fct_reorder(taxon_id, Estimate, median))
dat$sign <- NULL
dat %>%
  filter(p_adj_sig=="Yes")
dat <- dat %>%
  rename(`P-value`=p_val, 
         PFDR = p_adj,
         `Significant (PFDR<0.1)` = p_adj_sig,
         `Standard error` = `Std. Error`)
dat

#Filter on prevalence here
lm_df_filter01 <- dat %>% 
  filter(`%_PreTxLTR`>0.1 & `%_Healthy Control`>0.1)
lm_df_filter01
lm_df_filter001 <- dat %>% 
  filter(`%_PreTxLTR`>0.01 & `%_Healthy Control`>0.01)
lm_df_filter001

#VFDB
meta_liver <- CDmeta %>%
  select(ID, Timepoint_All, Age, BMI, Gender, Smoking, PPI, Laxative, Antibiotics) %>%
  filter(Timepoint_All %in% c("Healthy Control","PreTxLTR_TxL")) %>%
  mutate(Group=relevel(factor(Timepoint_All), ref="Healthy Control")) %>%
  select(-Timepoint_All)
summary(meta_liver$Group)
# subset abundance table to focal samples
ftbl_rclr <- ftbl_rclr_vfdb[,colnames(ftbl_rclr_vfdb) %in% meta_liver$ID] 
ftbl_rclr <- t(ftbl_rclr)
ftbl_rclr_PA <- data.frame(ftbl_rclr)

for (cn in colnames(ftbl_rclr_PA)) {
  ftbl_rclr_PA[[cn]][ftbl_rclr_PA[[cn]] > 0] <- 1
  ftbl_rclr_PA[[cn]][ftbl_rclr_PA[[cn]] <= 0] <- 1
}
ftbl_rclr_PA[is.na(ftbl_rclr_PA)] <- 0
ftbl_rclr_PA <- ftbl_rclr_PA[,colSums(ftbl_rclr_PA)>0]
# Species - Taxon-specific linear models 

glm_data <- #
  glm_data <- data.frame(ftbl_rclr_PA) %>%
  rownames_to_column("ID") %>%
  left_join(meta_liver, by="ID")

lm_ls <- vector("list", ncol(ftbl_rclr_PA))
names(lm_ls) <- colnames(ftbl_rclr_PA)
for(taxon in colnames(ftbl_rclr_PA)) {
  tryCatch({
    print(taxon)
    m <- glm(glm_data[,taxon] ~ Group + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics, data=glm_data[,c(taxon,"Group", "Age", "BMI", "Gender", "Smoking", "PPI", "Laxative", "Antibiotics")], family = binomial)
    mm <- coef(summary(m))[2,c(1,2,4)]
    names(mm)[3] <- "p_val"
    a <- tapply(glm_data[,taxon], glm_data$Group, sum)
    
    mm[4] <- a[1]
    names(mm)[4] <- paste0("n_", names(a)[1])
    mm[5] <- a[1] / summary(glm_data$Group)[1]
    names(mm)[5] <- paste0("%_", names(a)[1])
    mm[6] <- a[2] 
    names(mm)[6] <- paste0("n_", names(a)[2])
    mm[7] <- a[2] / summary(glm_data$Group)[2]
    names(mm)[7] <- paste0("%_", names(a)[2])
    lm_ls[[taxon]] <- mm
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}

# ERROR : contrasts can be applied only to factors with 2 or more levels
# This is caused by to few samples in e.g. Smoking variable
lm_ls[sapply(lm_ls, is.null)] <- NULL

#FDR correction
lm_df <- lm_ls %>%
  bind_rows(.id="taxon_id") %>%
  mutate(p_adj=p.adjust(p_val, "BH"))

dat <- lm_df %>%
  mutate(sign=sign(Estimate),
         Direction=ifelse(sign=="1","Increased","Decreased"),
         p_adj_sig=ifelse(p_adj<0.1, "Yes", "No"),
         taxon_id=fct_reorder(taxon_id, Estimate, median))
dat$sign <- NULL
dat %>%
  filter(p_adj_sig=="Yes")
dat <- dat %>%
  rename(`P-value`=p_val, 
         PFDR = p_adj,
         `Significant (PFDR<0.1)` = p_adj_sig,
         `Standard error` = `Std. Error`)
dat

#Filter on prevalence here
lm_df_filter01 <- dat %>% 
  filter(`%_PreTxLTR`>0.1 & `%_Healthy Control`>0.1)
lm_df_filter01

lm_df_filter001 <- dat %>% 
  filter(`%_PreTxLTR`>0.01 & `%_Healthy Control`>0.01)
lm_df_filter001
```
```{r}
#3.8      DA ESRD vs HC----
meta_renal <- CDmeta %>%
  select(ID, Timepoint_All, Age, BMI, Gender, Smoking, PPI, Laxative, Antibiotics) %>%
  filter(Timepoint_All %in% c("Healthy Control","PreTxRTR_TxN")) %>%
  mutate(Group=relevel(factor(Timepoint_All), ref="Healthy Control")) %>%
  select(-Timepoint_All)

# subset abundance table to focal samples
ftbl_rclr <- ftbl_rclr_species[,colnames(ftbl_rclr_species) %in% meta_renal$ID] 
ftbl_rclr <- t(ftbl_rclr)
ftbl_rclr_df <- data.frame(ftbl_rclr)

# Species - Taxon-specific linear models 
lm_data <- #
  lm_data <- data.frame(ftbl_rclr) %>%
  rownames_to_column("ID") %>%
  left_join(meta_renal, by="ID")

lm_ls <- vector("list", ncol(ftbl_rclr))
names(lm_ls) <- colnames(ftbl_rclr)
for(taxon in colnames(ftbl_rclr)) {
  tryCatch({
    print(taxon)
    m <- lm(lm_data[,taxon] ~ Group + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics, data=lm_data[,c(taxon,"Group", "Age", "BMI", "Gender", "Smoking", "PPI", "Laxative", "Antibiotics")])
    
    mm <- coef(summary(m))[2,c(1,2,4)]
    names(mm)[3] <- "p_val"
    
    lm_ls[[taxon]] <- mm
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}

# ERROR : contrasts can be applied only to factors with 2 or more levels
# This is caused by to few samples in e.g. Smoking variable
lm_ls[sapply(lm_ls, is.null)] <- NULL

#FDR correction
lm_df <- lm_ls %>%
  bind_rows(.id="taxon_id") %>%
  mutate(p_adj=p.adjust(p_val, "BH"))

dat <- lm_df %>%
  mutate(sign=sign(Estimate),
         Direction=ifelse(sign=="1","Increased","Decreased"),
         p_adj_sig=ifelse(p_adj<0.1, "Yes", "No"),
         taxon_id=fct_reorder(taxon_id, Estimate, median)) 
dat$sign <- NULL
dat %>%
  filter(p_adj_sig=="Yes")
dat <- left_join(dat, Healthy, by="taxon_id")
dat %>%
  filter(p_adj_sig=="Yes")
dat

#Pathways
meta_renal <- CDmeta_All %>%
  select(ID, Timepoint_All, Age, BMI, Gender, Smoking, PPI, Laxative, Antibiotics) %>%
  filter(Timepoint_All %in% c("Healthy Control","PreTxRTR_TxN")) %>%
  mutate(Group=relevel(factor(Timepoint_All), ref="Healthy Control")) %>%
  select(-Timepoint_All)

# subset abundance table to focal samples
ftbl_rclr <- ftbl_rclr_pwys[,colnames(ftbl_rclr_pwys) %in% meta_renal$ID] 
ftbl_rclr <- t(ftbl_rclr)

# Species - Taxon-specific linear models 

lm_data <- #
  lm_data <- data.frame(ftbl_rclr) %>%
  rownames_to_column("ID") %>%
  left_join(meta_renal, by="ID")

lm_ls <- vector("list", ncol(ftbl_rclr))
names(lm_ls) <- colnames(ftbl_rclr)
for(taxon in colnames(ftbl_rclr)) {
  tryCatch({
    print(taxon)
    m <- lm(lm_data[,taxon] ~ Group + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics, data=lm_data[,c(taxon,"Group", "Age", "BMI", "Gender", "Smoking", "PPI", "Laxative", "Antibiotics")])
    
    mm <- coef(summary(m))[2,c(1,2,4)]
    names(mm)[3] <- "p_val"
    
    lm_ls[[taxon]] <- mm
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}

# ERROR : contrasts can be applied only to factors with 2 or more levels
# This is caused by to few samples in e.g. Smoking variable
lm_ls[sapply(lm_ls, is.null)] <- NULL

#FDR correction
lm_df <- lm_ls %>%
  bind_rows(.id="taxon_id") %>%
  mutate(p_adj=p.adjust(p_val, "BH"))

dat <- lm_df %>%
  mutate(sign=sign(Estimate),
         Direction=ifelse(sign=="1","Increased","Decreased"),
         p_adj_sig=ifelse(p_adj<0.1, "Yes", "No"),
         taxon_id=fct_reorder(taxon_id, Estimate, median))
dat$sign <- NULL
dat
```
```{r}
#3.9      DA ESRD vs HC CARD VFDB PA----
#CARD
meta_renal <- CDmeta %>%
  select(ID, Timepoint_All, Age, BMI, Gender, Smoking, PPI, Laxative, Antibiotics) %>%
  filter(Timepoint_All %in% c("Healthy Control","PreTxRTR_TxN")) %>%
  mutate(Group=relevel(factor(Timepoint_All), ref="Healthy Control")) %>%
  select(-Timepoint_All)
summary(meta_renal$Group)
# subset abundance table to focal samples
ftbl_rclr <- ftbl_rclr_card[,colnames(ftbl_rclr_card) %in% meta_renal$ID] 
ftbl_rclr <- t(ftbl_rclr)
#ftbl_rclr_df <- data.frame(ftbl_rclr)
#sum(is.na(ftbl_rclr_df$gb.ACA23185_1.ARO_3000194.tetW__Bifidobacterium_longum_)
#CDcard_All <- data.frame(ftbl_rclr)
ftbl_rclr_PA <- data.frame(ftbl_rclr)

for (cn in colnames(ftbl_rclr_PA)) {
  ftbl_rclr_PA[[cn]][ftbl_rclr_PA[[cn]] > 0] <- 1
  ftbl_rclr_PA[[cn]][ftbl_rclr_PA[[cn]] <= 0] <- 1
}
ftbl_rclr_PA[is.na(ftbl_rclr_PA)] <- 0
ftbl_rclr_PA <- ftbl_rclr_PA[,colSums(ftbl_rclr_PA)>0]

glm_data <- #
  glm_data <- data.frame(ftbl_rclr_PA) %>%
  rownames_to_column("ID") %>%
  left_join(meta_renal, by="ID")

lm_ls <- vector("list", ncol(ftbl_rclr_PA))
names(lm_ls) <- colnames(ftbl_rclr_PA)
for(taxon in colnames(ftbl_rclr_PA)) {
  tryCatch({
    print(taxon)
    m <- glm(glm_data[,taxon] ~ Group + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics, data=glm_data[,c(taxon,"Group", "Age", "BMI", "Gender", "Smoking", "PPI", "Laxative", "Antibiotics")], family = binomial)
    mm <- coef(summary(m))[2,c(1,2,4)]
    names(mm)[3] <- "p_val"
    a <- tapply(glm_data[,taxon], glm_data$Group, sum)
    
    mm[4] <- a[1]
    names(mm)[4] <- paste0("n_", names(a)[1])
    mm[5] <- a[1] / summary(glm_data$Group)[1]
    names(mm)[5] <- paste0("%_", names(a)[1])
    mm[6] <- a[2] 
    names(mm)[6] <- paste0("n_", names(a)[2])
    mm[7] <- a[2] / summary(glm_data$Group)[2]
    names(mm)[7] <- paste0("%_", names(a)[2])
    lm_ls[[taxon]] <- mm
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}

# ERROR : contrasts can be applied only to factors with 2 or more levels
# This is caused by to few samples in e.g. Smoking variable
lm_ls[sapply(lm_ls, is.null)] <- NULL

#FDR correction
lm_df <- lm_ls %>%
  bind_rows(.id="taxon_id") %>%
  mutate(p_adj=p.adjust(p_val, "BH"))

dat <- lm_df %>%
  mutate(sign=sign(Estimate),
         Direction=ifelse(sign=="1","Increased","Decreased"),
         p_adj_sig=ifelse(p_adj<0.1, "Yes", "No"),
         taxon_id=fct_reorder(taxon_id, Estimate, median))
dat$sign <- NULL

#Filter on prevalence here
lm_df_filter01 <- dat %>% 
  filter(`%_PreTxRTR`>0.1 & `%_Healthy Control`>0.1)
summary(as.factor(lm_df_filter01$`Significant (PFDR<0.1)`))
lm_df_filter01
lm_df_filter001 <- dat %>% 
  filter(`%_PreTxRTR`>0.01 & `%_Healthy Control`>0.01)
summary(as.factor(lm_df_filter001$`Significant (PFDR<0.1)`))
lm_df_filter001

#VFDB
meta_renal <- CDmeta %>%
  select(ID, Timepoint_All, Age, BMI, Gender, Smoking, PPI, Laxative, Antibiotics) %>%
  filter(Timepoint_All %in% c("Healthy Control","PreTxRTR_TxN")) %>%
  mutate(Group=relevel(factor(Timepoint_All), ref="Healthy Control")) %>%
  select(-Timepoint_All)
summary(meta_renal$Group)
# subset abundance table to focal samples
ftbl_rclr <- ftbl_rclr_vfdb[,colnames(ftbl_rclr_vfdb) %in% meta_renal$ID] 
ftbl_rclr <- t(ftbl_rclr)
ftbl_rclr_PA <- data.frame(ftbl_rclr)

for (cn in colnames(ftbl_rclr_PA)) {
  ftbl_rclr_PA[[cn]][ftbl_rclr_PA[[cn]] > 0] <- 1
  ftbl_rclr_PA[[cn]][ftbl_rclr_PA[[cn]] <= 0] <- 1
}
ftbl_rclr_PA[is.na(ftbl_rclr_PA)] <- 0
ftbl_rclr_PA <- ftbl_rclr_PA[,colSums(ftbl_rclr_PA)>0]
# Species - Taxon-specific linear models 
# use meta_renal or meta_renal
glm_data <- #
  glm_data <- data.frame(ftbl_rclr_PA) %>%
  rownames_to_column("ID") %>%
  left_join(meta_renal, by="ID")

lm_ls <- vector("list", ncol(ftbl_rclr_PA))
names(lm_ls) <- colnames(ftbl_rclr_PA)
for(taxon in colnames(ftbl_rclr_PA)) {
  tryCatch({
    print(taxon)
    m <- glm(glm_data[,taxon] ~ Group + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics, data=glm_data[,c(taxon,"Group", "Age", "BMI", "Gender", "Smoking", "PPI", "Laxative", "Antibiotics")], family = binomial)
    mm <- coef(summary(m))[2,c(1,2,4)]
    names(mm)[3] <- "p_val"
    a <- tapply(glm_data[,taxon], glm_data$Group, sum)
    
    mm[4] <- a[1]
    names(mm)[4] <- paste0("n_", names(a)[1])
    mm[5] <- a[1] / summary(glm_data$Group)[1]
    names(mm)[5] <- paste0("%_", names(a)[1])
    mm[6] <- a[2] 
    names(mm)[6] <- paste0("n_", names(a)[2])
    mm[7] <- a[2] / summary(glm_data$Group)[2]
    names(mm)[7] <- paste0("%_", names(a)[2])
    lm_ls[[taxon]] <- mm
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}

# ERROR : contrasts can be applied only to factors with 2 or more levels
# This is caused by to few samples in e.g. Smoking variable
lm_ls[sapply(lm_ls, is.null)] <- NULL

#FDR correction
lm_df <- lm_ls %>%
  bind_rows(.id="taxon_id") %>%
  mutate(p_adj=p.adjust(p_val, "BH"))

dat <- lm_df %>%
  mutate(sign=sign(Estimate),
         Direction=ifelse(sign=="1","Increased","Decreased"),
         p_adj_sig=ifelse(p_adj<0.1, "Yes", "No"),
         taxon_id=fct_reorder(taxon_id, Estimate, median))
dat$sign <- NULL
dat %>%
  filter(p_adj_sig=="Yes")
dat

lm_df_filter01 <- dat %>% 
  filter(`%_PreTxRTR`>0.1 & `%_Healthy Control`>0.1)
summary(as.factor(lm_df_filter01$`Significant (PFDR<0.1)`))
lm_df_filter01
lm_df_filter001 <- dat %>% 
  filter(`%_PreTxRTR`>0.01 & `%_Healthy Control`>0.01)
summary(as.factor(lm_df_filter001$`Significant (PFDR<0.1)`))
lm_df_filter001
```
