---
title: "Immunosuppresive medication analysis"
author: Shixian Hu & Cas Swarte
output: html_notebook

# ==========================================================================================
#                       By: Weersma Group, TransplantLines (UMCG)
#
#                       UMCG Transplantlines Project data analysis
# ==========================================================================================
#                        Immunosuppresive medication analysis -
#
#           These codes performs differential abundance analysis for users vs. non-users 
#                           (results included in main Figure 5)
#
# ==========================================================================================
#
# NOTE: This is implementation on Mock Data published in this github repo, and is intended 
# for demonstration purposes only, the results are not identical to Figures in the manuscript
#
# NOTE2: Codes are intended to be run from root of this github repo, if running them from 
# different location, make sure to adjust setwd to appropriate location 
# (root of this github repo)
#
# ==========================================================================================
#
#                   make sure following packages are installed:
#             install.packages(c('foreach','ggplot2', 'dplyr','UpSetR',
#             'tidyverse','xlsx','ggplot2','ggplotify','ggpubr'))
#
# ==========================================================================================
---
```{r}
#Load packages
library(foreach)
library(ggplot2)
library(dplyr)
library(UpSetR)
library(tidyverse)
library(xlsx)
library(ggplot2)
library(ggplotify)
library(ggpubr)
library(plyr)
```
```{r}
#Load data
#Taxa
mock_taxa=read.csv("mock data/deicode_output/Mocks_Taxa_Filtered_rclr.csv", row.names=1)
#Pathways
mock_path=read.csv("mock data/deicode_output/Mocks_Pathways_Filtered_rclr.csv", row.names=1)

#Meta
tmp_covariate <- read.csv("mock_data/Mock_Meta_Final.csv", row.names=1)
tmp_covariate$ID <- row.names(tmp_covariate)
tmp_covariate$ID <- trimws(tmp_covariate$ID)
row.names(tmp_covariate) <- tmp_covariate$ID

#Prep dataframes
tmp_taxa=as.data.frame(t(mock_taxa))
row.names(tmp_taxa) <- gsub("MOCK_","", row.names(tmp_taxa))
tmp_pwys=as.data.frame(t(mock_path))
row.names(tmp_pwys) <- gsub("MOCK_","", row.names(tmp_pwys))
tmp_taxa=tmp_taxa[rownames(tmp_taxa) %in% rownames(tmp_covariate),]
tmp_pwys=tmp_pwys[rownames(tmp_pwys) %in% rownames(tmp_covariate),]
```
```{r}
#Test medication individually
#Prednisolone - Taxonomy
taxa_result_pred = foreach(i=1:ncol(tmp_taxa),.combine = rbind) %do%  {
  tryCatch({
    taxon=colnames(tmp_taxa)[i]
    print(taxon)
    lm_data=merge(tmp_taxa[,taxon,drop=F],tmp_covariate,by="row.names",all=F)
    m <- lm(lm_data[,taxon] ~ Cross_sectional_samples + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics +
              Prednisolone , data=lm_data)
    mm <- as.data.frame(coef(summary(m)))
    mm=mm[rownames(mm)!="(Intercept)",]
    
    return.string=data.frame(Factor=rownames(mm),Estimate=mm$Estimate,SD=mm$`Std. Error`,Pvalue=mm$`Pr(>|t|)`,Taxa=taxon)
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
head(taxa_result_pred)

#Tacrolimus - Taxonomy
taxa_result_Tacrolimus = foreach(i=1:ncol(tmp_taxa),.combine = rbind) %do%  {
  tryCatch({
    taxon=colnames(tmp_taxa)[i]
    print(taxon)
    lm_data=merge(tmp_taxa[,taxon,drop=F],tmp_covariate,by="row.names",all=F)
    m <- lm(lm_data[,taxon] ~ Cross_sectional_samples + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics +
              Tacrolimus , data=lm_data)
    mm <- as.data.frame(coef(summary(m)))
    mm=mm[rownames(mm)!="(Intercept)",]
    
    return.string=data.frame(Factor=rownames(mm),Estimate=mm$Estimate,SD=mm$`Std. Error`,Pvalue=mm$`Pr(>|t|)`,Taxa=taxon)
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
head(taxa_result_Tacrolimus)

#Mycophenolic acid - Taxonomy
taxa_result_Mycophenolic_acid = foreach(i=1:ncol(tmp_taxa),.combine = rbind) %do%  {
  tryCatch({
    taxon=colnames(tmp_taxa)[i]
    print(taxon)
    lm_data=merge(tmp_taxa[,taxon,drop=F],tmp_covariate,by="row.names",all=F)
    m <- lm(lm_data[,taxon] ~ Cross_sectional_samples + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics +
              Mycophenolic_acid, data=lm_data)
    mm <- as.data.frame(coef(summary(m)))
    mm=mm[rownames(mm)!="(Intercept)",]
    
    return.string=data.frame(Factor=rownames(mm),Estimate=mm$Estimate,SD=mm$`Std. Error`,Pvalue=mm$`Pr(>|t|)`,Taxa=taxon)
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
head(taxa_result_Mycophenolic_acid)

#Ciclosporin - Taxonomy
taxa_result_Ciclosporine = foreach(i=1:ncol(tmp_taxa),.combine = rbind) %do%  {
  tryCatch({
    taxon=colnames(tmp_taxa)[i]
    print(taxon)
    lm_data=merge(tmp_taxa[,taxon,drop=F],tmp_covariate,by="row.names",all=F)
    m <- lm(lm_data[,taxon] ~ Cross_sectional_samples + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics +
              Ciclosporine, data=lm_data)
    mm <- as.data.frame(coef(summary(m)))
    mm=mm[rownames(mm)!="(Intercept)",]
    
    return.string=data.frame(Factor=rownames(mm),Estimate=mm$Estimate,SD=mm$`Std. Error`,Pvalue=mm$`Pr(>|t|)`,Taxa=taxon)
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
head(taxa_result_Ciclosporine)

#Azathioprine - Taxonomy
taxa_result_Azathioprine = foreach(i=1:ncol(tmp_taxa),.combine = rbind) %do%  {
  tryCatch({
    taxon=colnames(tmp_taxa)[i]
    print(taxon)
    lm_data=merge(tmp_taxa[,taxon,drop=F],tmp_covariate,by="row.names",all=F)
    m <- lm(lm_data[,taxon] ~ Cross_sectional_samples + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics +
              Azathioprine, data=lm_data)
    mm <- as.data.frame(coef(summary(m)))
    mm=mm[rownames(mm)!="(Intercept)",]
    
    return.string=data.frame(Factor=rownames(mm),Estimate=mm$Estimate,SD=mm$`Std. Error`,Pvalue=mm$`Pr(>|t|)`,Taxa=taxon)
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
head(taxa_result_Azathioprine)

#Case control - Taxonomy
taxa_result_case_control = foreach(i=1:ncol(tmp_taxa),.combine = rbind) %do%  {
  tryCatch({
    taxon=colnames(tmp_taxa)[i]
    print(taxon)
    lm_data=merge(tmp_taxa[,taxon,drop=F],tmp_covariate,by="row.names",all=F)
    m <- lm(lm_data[,taxon] ~ Cross_sectional_samples + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics, data=lm_data)
    mm <- as.data.frame(coef(summary(m)))
    mm=mm[rownames(mm)!="(Intercept)",]
    
    return.string=data.frame(Factor=rownames(mm),Estimate=mm$Estimate,SD=mm$`Std. Error`,Pvalue=mm$`Pr(>|t|)`,Taxa=taxon)
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
head(taxa_result_case_control)

#Prednisolone - Pathways
pathway_result_pred = foreach(i=1:ncol(tmp_pwys),.combine = rbind) %do%  {
  tryCatch({
    taxon=colnames(tmp_pwys)[i]
    print(taxon)
    lm_data=merge(tmp_pwys[,taxon,drop=F],tmp_covariate,by="row.names",all=F)
    m <- lm(lm_data[,taxon] ~ Cross_sectional_samples + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics +
              Prednisolone, data=lm_data)
    mm <- as.data.frame(coef(summary(m)))
    mm=mm[rownames(mm)!="(Intercept)",]
    
    return.string=data.frame(Factor=rownames(mm),Estimate=mm$Estimate,SD=mm$`Std. Error`,Pvalue=mm$`Pr(>|t|)`,Taxa=taxon)
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
head(pathway_result_pred)

#Tacrolimus - Pathways
pathway_result_Tacrolimus = foreach(i=1:ncol(tmp_pwys),.combine = rbind) %do%  {
  tryCatch({
    taxon=colnames(tmp_pwys)[i]
    print(taxon)
    lm_data=merge(tmp_pwys[,taxon,drop=F],tmp_covariate,by="row.names",all=F)
    m <- lm(lm_data[,taxon] ~ Cross_sectional_samples + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics +
              Tacrolimus, data=lm_data)
    mm <- as.data.frame(coef(summary(m)))
    mm=mm[rownames(mm)!="(Intercept)",]
    
    return.string=data.frame(Factor=rownames(mm),Estimate=mm$Estimate,SD=mm$`Std. Error`,Pvalue=mm$`Pr(>|t|)`,Taxa=taxon)
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
head(pathway_result_Tacrolimus)

#Mycophenolic acid - Pathways
pathway_result_Mycophenolic_acid = foreach(i=1:ncol(tmp_pwys),.combine = rbind) %do%  {
  tryCatch({
    taxon=colnames(tmp_pwys)[i]
    print(taxon)
    lm_data=merge(tmp_pwys[,taxon,drop=F],tmp_covariate,by="row.names",all=F)
    m <- lm(lm_data[,taxon] ~ Cross_sectional_samples + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics +
              Mycophenolic_acid, data=lm_data)
    mm <- as.data.frame(coef(summary(m)))
    mm=mm[rownames(mm)!="(Intercept)",]
    
    return.string=data.frame(Factor=rownames(mm),Estimate=mm$Estimate,SD=mm$`Std. Error`,Pvalue=mm$`Pr(>|t|)`,Taxa=taxon)
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
head(pathway_result_Mycophenolic_acid)

#Ciclosporin - Pathways
pathway_result_Ciclosporine = foreach(i=1:ncol(tmp_pwys),.combine = rbind) %do%  {
  tryCatch({
    taxon=colnames(tmp_pwys)[i]
    print(taxon)
    lm_data=merge(tmp_pwys[,taxon,drop=F],tmp_covariate,by="row.names",all=F)
    m <- lm(lm_data[,taxon] ~ Cross_sectional_samples + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics +
              Ciclosporine, data=lm_data)
    mm <- as.data.frame(coef(summary(m)))
    mm=mm[rownames(mm)!="(Intercept)",]
    
    return.string=data.frame(Factor=rownames(mm),Estimate=mm$Estimate,SD=mm$`Std. Error`,Pvalue=mm$`Pr(>|t|)`,Taxa=taxon)
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
head(pathway_result_Ciclosporine)

#Azathioprine - Pathways
pathway_result_Azathioprine = foreach(i=1:ncol(tmp_pwys),.combine = rbind) %do%  {
  tryCatch({
    taxon=colnames(tmp_pwys)[i]
    print(taxon)
    lm_data=merge(tmp_pwys[,taxon,drop=F],tmp_covariate,by="row.names",all=F)
    m <- lm(lm_data[,taxon] ~ Cross_sectional_samples + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics +
              Azathioprine, data=lm_data)
    mm <- as.data.frame(coef(summary(m)))
    mm=mm[rownames(mm)!="(Intercept)",]
    
    return.string=data.frame(Factor=rownames(mm),Estimate=mm$Estimate,SD=mm$`Std. Error`,Pvalue=mm$`Pr(>|t|)`,Taxa=taxon)
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
head(pathway_result_Azathioprine)

#Case-control - Pathways
pathway_result_case_control = foreach(i=1:ncol(tmp_pwys),.combine = rbind) %do%  {
  tryCatch({
    taxon=colnames(tmp_pwys)[i]
    print(taxon)
    lm_data=merge(tmp_pwys[,taxon,drop=F],tmp_covariate,by="row.names",all=F)
    m <- lm(lm_data[,taxon] ~ Cross_sectional_samples + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics, data=lm_data)
    mm <- as.data.frame(coef(summary(m)))
    mm=mm[rownames(mm)!="(Intercept)",]
    
    return.string=data.frame(Factor=rownames(mm),Estimate=mm$Estimate,SD=mm$`Std. Error`,Pvalue=mm$`Pr(>|t|)`,Taxa=taxon)
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
head(pathway_result_case_control)
```
```{r}
#FDR correction
taxa_result_pred$FDR=p.adjust(taxa_result_pred$Pvalue,method = "BH")
#taxa_result_pred=taxa_result_pred[taxa_result_pred$Factor=="Prednisoloneyes" & taxa_result_pred$FDR<0.1,]
taxa_result_Tacrolimus$FDR=p.adjust(taxa_result_Tacrolimus$Pvalue,method = "BH")
#taxa_result_Tacrolimus=taxa_result_Tacrolimus[taxa_result_Tacrolimus$Factor=="Tacrolimusyes" & taxa_result_Tacrolimus$FDR<0.1,]
taxa_result_Mycophenolic_acid$FDR=p.adjust(taxa_result_Mycophenolic_acid$Pvalue,method = "BH")
#taxa_result_Mycophenolic_acid=taxa_result_Mycophenolic_acid[taxa_result_Mycophenolic_acid$Factor=="Mycophenolic_acidyes" & taxa_result_Mycophenolic_acid$FDR<0.1,]
taxa_result_Ciclosporine$FDR=p.adjust(taxa_result_Ciclosporine$Pvalue,method = "BH")
#taxa_result_Ciclosporine=taxa_result_Ciclosporine[taxa_result_Ciclosporine$Factor=="Ciclosporineyes" & taxa_result_Ciclosporine$FDR<0.1,]
taxa_result_Azathioprine$FDR=p.adjust(taxa_result_Azathioprine$Pvalue,method = "BH")
#taxa_result_Azathioprine=taxa_result_Azathioprine[taxa_result_Azathioprine$Factor=="Azathioprineyes" & taxa_result_Azathioprine$FDR<0.1,]
taxa_result_case_control$FDR=p.adjust(taxa_result_case_control$Pvalue,method = "BH")
#taxa_result_case_control=taxa_result_case_control[taxa_result_case_control$Factor=="Cross_sectional_samplesYes" & taxa_result_case_control$FDR<0.1,]

pathway_result_pred$FDR=p.adjust(pathway_result_pred$Pvalue,method = "BH")
#pathway_result_pred=pathway_result_pred[pathway_result_pred$Factor=="Prednisoloneyes" & pathway_result_pred$FDR<0.1,]
pathway_result_Tacrolimus$FDR=p.adjust(pathway_result_Tacrolimus$Pvalue,method = "BH")
#pathway_result_Tacrolimus=pathway_result_Tacrolimus[pathway_result_Tacrolimus$Factor=="Tacrolimusyes" & pathway_result_Tacrolimus$FDR<0.1,]
pathway_result_Mycophenolic_acid$FDR=p.adjust(pathway_result_Mycophenolic_acid$Pvalue,method = "BH")
#pathway_result_Mycophenolic_acid=pathway_result_Mycophenolic_acid[pathway_result_Mycophenolic_acid$Factor=="Mycophenolic_acidyes" & pathway_result_Mycophenolic_acid$FDR<0.1,]
pathway_result_Ciclosporine$FDR=p.adjust(pathway_result_Ciclosporine$Pvalue,method = "BH")
#pathway_result_Ciclosporine=pathway_result_Ciclosporine[pathway_result_Ciclosporine$Factor=="Ciclosporineyes" & pathway_result_Ciclosporine$FDR<0.1,]
pathway_result_Azathioprine$FDR=p.adjust(pathway_result_Azathioprine$Pvalue,method = "BH")
#pathway_result_Azathioprine=pathway_result_Azathioprine[pathway_result_Azathioprine$Factor=="Azathioprineyes" & pathway_result_Azathioprine$FDR<0.1,]
pathway_result_case_control$FDR=p.adjust(pathway_result_case_control$Pvalue,method = "BH")
#pathway_result_case_control=pathway_result_case_control[pathway_result_case_control$Factor=="Cross_sectional_samplesYes" & pathway_result_case_control$FDR<0.1,]
```
```{r}
# test medication combinations
tmp_covariate$group1=NA
tmp_covariate$group1[tmp_covariate$Mycophenolic_acid=="yes" & tmp_covariate$Tacrolimus=="yes" & tmp_covariate$Prednisolone=="yes"]="yes"
tmp_covariate$group1[is.na(tmp_covariate$group1)]="no"

tmp_covariate$group2=NA
tmp_covariate$group2[tmp_covariate$Mycophenolic_acid=="yes" & tmp_covariate$Tacrolimus=="yes"]="yes"
tmp_covariate$group2[is.na(tmp_covariate$group2)]="no"

tmp_covariate$group3=NA
tmp_covariate$group3[tmp_covariate$Tacrolimus=="yes" & tmp_covariate$Prednisolone=="yes"]="yes"
tmp_covariate$group3[is.na(tmp_covariate$group3)]="no"

tmp_covariate$group4=NA
tmp_covariate$group4[tmp_covariate$Mycophenolic_acid=="yes"  & tmp_covariate$Prednisolone=="yes"]="yes"
tmp_covariate$group4[is.na(tmp_covariate$group4)]="no"

tmp_covariate$group5=NA
tmp_covariate$group5[tmp_covariate$Ciclosporine =="yes"  & tmp_covariate$Prednisolone=="yes"]="yes"
tmp_covariate$group5[is.na(tmp_covariate$group5)]="no"

#Test combincations of immunosuppresive medications - Taxonomy
taxa_result_group1 = foreach(i=1:ncol(tmp_taxa),.combine = rbind) %do%  {
  tryCatch({
    taxon=colnames(tmp_taxa)[i]
    print(taxon)
    lm_data=merge(tmp_taxa[,taxon,drop=F],tmp_covariate,by.x="row.names",by.y="ID",all=F)
    m <- lm(lm_data[,taxon] ~ Cross_sectional_samples + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics +
              group1 , data=lm_data)
    mm <- as.data.frame(coef(summary(m)))
    mm=mm[rownames(mm)!="(Intercept)",]
    
    return.string=data.frame(Factor=rownames(mm),Estimate=mm$Estimate,SD=mm$`Std. Error`,Pvalue=mm$`Pr(>|t|)`,Taxa=taxon)
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
head(taxa_result_group1)
taxa_result_group2 = foreach(i=1:ncol(tmp_taxa),.combine = rbind) %do%  {
  tryCatch({
    taxon=colnames(tmp_taxa)[i]
    print(taxon)
    lm_data=merge(tmp_taxa[,taxon,drop=F],tmp_covariate,by.x="row.names",by.y="ID",all=F)
    m <- lm(lm_data[,taxon] ~ Cross_sectional_samples + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics +
              group2 , data=lm_data)
    mm <- as.data.frame(coef(summary(m)))
    mm=mm[rownames(mm)!="(Intercept)",]
    
    return.string=data.frame(Factor=rownames(mm),Estimate=mm$Estimate,SD=mm$`Std. Error`,Pvalue=mm$`Pr(>|t|)`,Taxa=taxon)
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
head(taxa_result_group2)
taxa_result_group3 = foreach(i=1:ncol(tmp_taxa),.combine = rbind) %do%  {
  tryCatch({
    taxon=colnames(tmp_taxa)[i]
    print(taxon)
    lm_data=merge(tmp_taxa[,taxon,drop=F],tmp_covariate,by.x="row.names",by.y="ID",all=F)
    m <- lm(lm_data[,taxon] ~ Cross_sectional_samples + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics +
              group3 , data=lm_data)
    mm <- as.data.frame(coef(summary(m)))
    mm=mm[rownames(mm)!="(Intercept)",]
    
    return.string=data.frame(Factor=rownames(mm),Estimate=mm$Estimate,SD=mm$`Std. Error`,Pvalue=mm$`Pr(>|t|)`,Taxa=taxon)
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
head(taxa_result_group3)
taxa_result_group4 = foreach(i=1:ncol(tmp_taxa),.combine = rbind) %do%  {
  tryCatch({
    taxon=colnames(tmp_taxa)[i]
    print(taxon)
    lm_data=merge(tmp_taxa[,taxon,drop=F],tmp_covariate,by.x="row.names",by.y="ID",all=F)
    m <- lm(lm_data[,taxon] ~ Cross_sectional_samples + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics +
              group4 , data=lm_data)
    mm <- as.data.frame(coef(summary(m)))
    mm=mm[rownames(mm)!="(Intercept)",]
    
    return.string=data.frame(Factor=rownames(mm),Estimate=mm$Estimate,SD=mm$`Std. Error`,Pvalue=mm$`Pr(>|t|)`,Taxa=taxon)
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
head(taxa_result_group4)
taxa_result_group5 = foreach(i=1:ncol(tmp_taxa),.combine = rbind) %do%  {
  tryCatch({
    taxon=colnames(tmp_taxa)[i]
    print(taxon)
    lm_data=merge(tmp_taxa[,taxon,drop=F],tmp_covariate,by.x="row.names",by.y="ID",all=F)
    m <- lm(lm_data[,taxon] ~ Cross_sectional_samples + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics +
              group5 , data=lm_data)
    mm <- as.data.frame(coef(summary(m)))
    mm=mm[rownames(mm)!="(Intercept)",]
    
    return.string=data.frame(Factor=rownames(mm),Estimate=mm$Estimate,SD=mm$`Std. Error`,Pvalue=mm$`Pr(>|t|)`,Taxa=taxon)
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
head(taxa_result_group5)

#Test combincations of immunosuppresive medications - Pathways
pathway_result_group1 = foreach(i=1:ncol(tmp_pwys),.combine = rbind) %do%  {
  tryCatch({
    taxon=colnames(tmp_pwys)[i]
    print(taxon)
    lm_data=merge(tmp_pwys[,taxon,drop=F],tmp_covariate,by.x="row.names",by.y="ID",all=F)
    m <- lm(lm_data[,taxon] ~ Cross_sectional_samples + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics +
              group1 , data=lm_data)
    mm <- as.data.frame(coef(summary(m)))
    mm=mm[rownames(mm)!="(Intercept)",]
    
    return.string=data.frame(Factor=rownames(mm),Estimate=mm$Estimate,SD=mm$`Std. Error`,Pvalue=mm$`Pr(>|t|)`,Taxa=taxon)
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
head(pathway_result_group1)
pathway_result_group2 = foreach(i=1:ncol(tmp_pwys),.combine = rbind) %do%  {
  tryCatch({
    taxon=colnames(tmp_pwys)[i]
    print(taxon)
    lm_data=merge(tmp_pwys[,taxon,drop=F],tmp_covariate,by.x="row.names",by.y="ID",all=F)
    m <- lm(lm_data[,taxon] ~ Cross_sectional_samples + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics +
              group2 , data=lm_data)
    mm <- as.data.frame(coef(summary(m)))
    mm=mm[rownames(mm)!="(Intercept)",]
    
    return.string=data.frame(Factor=rownames(mm),Estimate=mm$Estimate,SD=mm$`Std. Error`,Pvalue=mm$`Pr(>|t|)`,Taxa=taxon)
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
head(pathway_result_group2)
pathway_result_group3 = foreach(i=1:ncol(tmp_pwys),.combine = rbind) %do%  {
  tryCatch({
    taxon=colnames(tmp_pwys)[i]
    print(taxon)
    lm_data=merge(tmp_pwys[,taxon,drop=F],tmp_covariate,by.x="row.names",by.y="ID",all=F)
    m <- lm(lm_data[,taxon] ~ Cross_sectional_samples + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics +
              group3 , data=lm_data)
    mm <- as.data.frame(coef(summary(m)))
    mm=mm[rownames(mm)!="(Intercept)",]
    
    return.string=data.frame(Factor=rownames(mm),Estimate=mm$Estimate,SD=mm$`Std. Error`,Pvalue=mm$`Pr(>|t|)`,Taxa=taxon)
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
head(pathway_result_group3)
pathway_result_group4 = foreach(i=1:ncol(tmp_pwys),.combine = rbind) %do%  {
  tryCatch({
    taxon=colnames(tmp_pwys)[i]
    print(taxon)
    lm_data=merge(tmp_pwys[,taxon,drop=F],tmp_covariate,by.x="row.names",by.y="ID",all=F)
    m <- lm(lm_data[,taxon] ~ Cross_sectional_samples + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics +
              group4 , data=lm_data)
    mm <- as.data.frame(coef(summary(m)))
    mm=mm[rownames(mm)!="(Intercept)",]
    
    return.string=data.frame(Factor=rownames(mm),Estimate=mm$Estimate,SD=mm$`Std. Error`,Pvalue=mm$`Pr(>|t|)`,Taxa=taxon)
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
head(pathway_result_group4)
pathway_result_group5 = foreach(i=1:ncol(tmp_pwys),.combine = rbind) %do%  {
  tryCatch({
    taxon=colnames(tmp_pwys)[i]
    print(taxon)
    lm_data=merge(tmp_pwys[,taxon,drop=F],tmp_covariate,by.x="row.names",by.y="ID",all=F)
    m <- lm(lm_data[,taxon] ~ Cross_sectional_samples + Age + BMI + Gender + Smoking + PPI + Laxative + Antibiotics +
              group5 , data=lm_data)
    mm <- as.data.frame(coef(summary(m)))
    mm=mm[rownames(mm)!="(Intercept)",]
    
    return.string=data.frame(Factor=rownames(mm),Estimate=mm$Estimate,SD=mm$`Std. Error`,Pvalue=mm$`Pr(>|t|)`,Taxa=taxon)
    
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}
head(pathway_result_group5)
```
```{r}
#FDR correction
taxa_result_group1$FDR=p.adjust(taxa_result_group1$Pvalue,method = "BH")
taxa_result_group2$FDR=p.adjust(taxa_result_group2$Pvalue,method = "BH")
taxa_result_group3$FDR=p.adjust(taxa_result_group3$Pvalue,method = "BH")
taxa_result_group4$FDR=p.adjust(taxa_result_group4$Pvalue,method = "BH")
taxa_result_group5$FDR=p.adjust(taxa_result_group5$Pvalue,method = "BH")

pathway_result_group1$FDR=p.adjust(pathway_result_group1$Pvalue,method = "BH")
pathway_result_group2$FDR=p.adjust(pathway_result_group2$Pvalue,method = "BH")
pathway_result_group3$FDR=p.adjust(pathway_result_group3$Pvalue,method = "BH")
pathway_result_group4$FDR=p.adjust(pathway_result_group4$Pvalue,method = "BH")
pathway_result_group5$FDR=p.adjust(pathway_result_group5$Pvalue,method = "BH")
```
```{r}
#Create main figure 5
taxa_result_per=read.table("mock_data/Taxa.results_per.txt",sep = "\t",check.names = F,header = T,stringsAsFactors = F)
pathway_result_per=read.table("mock_data/Pathway.results_per.txt",sep = "\t",check.names = F,header = T,stringsAsFactors = F)
taxa_result_per$Factor <- as.factor(taxa_result_per$Factor)
taxa_result_per$Factor <- revalue(taxa_result_per$Factor, 
                                  c("azathioprineyes"="Azathioprine", 
                                    "ciclosporineyes"="Cyclosporin",
                                    "dum_predyes"="Prednisolone",
                                    "mycofenolzuuryes"="Mycophenolic acid",
                                    "tacrolimusyes"="Tacrolimus",
                                    "TypeMoreThan12MonthsYes"="Recipient vs. HC"))
summary(taxa_result_per$Factor)

pathway_result_per$Factor <- as.factor(pathway_result_per$Factor)
pathway_result_per$Factor <- revalue(pathway_result_per$Factor, 
                                     c("azathioprineyes"="Azathioprine", 
                                       "ciclosporineyes"="Cyclosporin",
                                       "dum_predyes"="Prednisolone",
                                       "mycofenolzuuryes"="Mycophenolic acid",
                                       "tacrolimusyes"="Tacrolimus",
                                       "TypeMoreThan12MonthsYes"="Recipient vs. HC"))
summary(pathway_result_per$Factor)

#Figure 5A and 5B - upsetR
cols=length(unique(taxa_result_per$Taxa))
rows=length(unique(taxa_result_per$Factor))
taxa_upset=matrix(nrow = rows,ncol = cols)
colnames(taxa_upset)=unique(taxa_result_per$Taxa)
rownames(taxa_upset)=unique(taxa_result_per$Factor)

for(i in unique(taxa_result_per$Factor)){
  tmp.medication=taxa_result_per[taxa_result_per$Factor==i,]
  for(n in tmp.medication$Taxa){
    taxa_upset[rownames(taxa_upset)==i,colnames(taxa_upset)==n]=1
  }
}
taxa_upset[is.na(taxa_upset)]=0
taxa_upset=as.data.frame(t(taxa_upset))
#pdf("upset.bacteria.pdf")
UpsetR_Taxa <- upset(taxa_upset,sets = colnames(taxa_upset),sets.bar.color = "#56B4E9",point.size=3,
                     order.by = "freq",  keep.order = TRUE)
UpsetR_Test <- upset(taxa_upset,sets = colnames(taxa_upset),sets.bar.color = "#56B4E9",point.size=3,
                     order.by = "freq",  keep.order = TRUE)
#dev.off()
UpsetR_Taxa <- as.ggplot(upset(taxa_upset,sets = colnames(taxa_upset),sets.bar.color = "#56B4E9",point.size=3,
                               order.by = "freq",  keep.order = TRUE))

cols=length(unique(pathway_result_per$Taxa))
rows=length(unique(pathway_result_per$Factor))
pathway_upset=matrix(nrow = rows,ncol = cols)
colnames(pathway_upset)=unique(pathway_result_per$Taxa)
rownames(pathway_upset)=unique(pathway_result_per$Factor)

for(i in unique(pathway_result_per$Factor)){
  tmp.medication=pathway_result_per[pathway_result_per$Factor==i,]
  for(n in tmp.medication$Taxa){
    pathway_upset[rownames(pathway_upset)==i,colnames(pathway_upset)==n]=1
  }
}
pathway_upset[is.na(pathway_upset)]=0
pathway_upset=as.data.frame(t(pathway_upset))
#pdf("upset.pathway.pdf")
upset(pathway_upset,sets = colnames(pathway_upset),sets.bar.color = "#56B4E9",point.size=3,
      order.by = "freq",  keep.order = TRUE)
#dev.off()

UpsetR_Pathways <- as.ggplot(upset(taxa_upset,sets = colnames(taxa_upset),sets.bar.color = "#56B4E9",point.size=3,
                                   order.by = "freq",  keep.order = TRUE))
UpsetR_Pathways

#Figure 5C - Heatmap Taxa
Taxa_heatmap_edited <- read.xlsx("Taxa_heatmap_edited.xlsx",1)
summary(Taxa_heatmap_edited$Medication)

Taxa_heatmap_edited <-  Taxa_heatmap_edited %>% 
  mutate(group=fct_relevel(Medication, c("Prednisolone","Mycophenolic acid","Tacrolimus","Cyclosporin","Azathioprine","Recipient vs. HC")),
         taxon_id=fct_reorder(Taxon, Estimate, median))

Fig5C <- Taxa_heatmap_edited %>% ggplot(aes(y=group,x=taxon_id,fill=Estimate)) +
  #geom_tile(width=0.3) +
  geom_tile(colour="black", width=0.5, height=0.5) +
  scale_fill_gradient2(name="Effect size", low = "#1111AA", mid = "white", high = "#AA1111") +
  #geom_text(aes(label=Direction), size=3) +
  theme(panel.grid.major=element_blank(), 
        panel.grid.minor=element_blank(), 
        panel.background=element_rect(fill="white"),
        panel.border=element_rect(colour="black", fill=NA, size=1),
        axis.text.y = element_text(size=12, face="bold", colour = "black", hjust=0),
        axis.text.x = element_text(size=12, face="italic", colour = "black", hjust=1, angle=45),
        legend.text = element_text(size=12, face="bold", colour = "black"),
        legend.title =element_text(size=14, face="bold", colour = "black")) +
  labs(x=NULL, y=NULL) 
#scale_y_discrete(labels=setNames(dataForPWYSHeatmap2$Class, dataForPWYSHeatmap2$taxon_id))
Fig5C

#Figure 5D - Heatmap Pathways
pathway_classes <- read.table("mock_data/path_annotated_index_V3.txt", sep='\t',header=T, fill=T)
pathway_classes$taxon_id <- pathway_classes$MetaCyc_complete_name

#Filtered by estimate <= -0.1 or => 0.1)
Pathway_heatmap_edited <- read.xlsx("mock_data/Pathway_heatmap_edited_class.xlsx",1)
summary(Pathway_heatmap_edited$Medication)

Pathway_heatmap_edited <-  Pathway_heatmap_edited %>% 
  mutate(group=fct_relevel(Medication, c("Prednisolone","Mycophenolic acid","Tacrolimus","Cyclosporin","Azathioprine","Recipient vs. HC")),
         taxon_id=fct_reorder(Pathway, Estimate, median))
Pathway_heatmap_edited$Class <- as.character(Pathway_heatmap_edited$Class)

Fig5D <- Pathway_heatmap_edited %>% ggplot(aes(y=group,x=taxon_id,fill=Estimate)) +
  #geom_tile(width=0.3) +
  geom_tile(colour="black", width=0.5, height=0.5) +
  scale_fill_gradient2(name="Effect size", low = "#1111AA", mid = "white", high = "#AA1111") +
  #geom_text(aes(label=Direction), size=3) +
  theme(panel.grid.major=element_blank(), 
        panel.grid.minor=element_blank(), 
        panel.background=element_rect(fill="white"),
        panel.border=element_rect(colour="black", fill=NA, size=1),
        axis.text.y = element_text(size=12, face="bold", colour = "black", hjust=0),
        axis.text.x = element_text(size=8, face="bold", colour = "black", hjust=1, angle=45),
        legend.text = element_text(size=12, face="bold", colour = "black"),
        legend.title =element_text(size=14, face="bold", colour = "black")) +
  labs(x=NULL, y=NULL)+
  scale_x_discrete(labels=setNames(Pathway_heatmap_edited$Class, Pathway_heatmap_edited$Pathway))
Fig5D

Fig5D_Category <- Pathway_heatmap_edited %>% ggplot(aes(y=group,x=taxon_id,fill=Estimate)) +
  #geom_tile(width=0.3) +
  geom_tile(colour="black", width=0.5) +
  scale_fill_gradient2(name="Effect size", low = "#AA1111", mid = "white", high = "#1111AA") +
  geom_text(aes(label=Direction), size=3) +
  theme(panel.grid.major=element_blank(), 
        panel.grid.minor=element_blank(), 
        panel.background=element_rect(fill="white"),
        panel.border=element_rect(colour="black", fill=NA, size=1),
        axis.text.y = element_text(size=12, face="bold", colour = "black", hjust=0),
        axis.text.x = element_text(size=8, face="bold", colour = "black", hjust=1, angle=45),
        legend.text = element_text(size=12, face="bold", colour = "black"),
        legend.title =element_text(size=14, face="bold", colour = "black")) +
  labs(x=NULL, y=NULL)+
  scale_x_discrete(labels=setNames(Pathway_heatmap_edited$Class, Pathway_heatmap_edited$Pathway))
Fig5D_Category

#Figure 5 arrange
Fig5AB <- ggarrange(UpsetR_Taxa, UpsetR_Pathways, nrow=1, align=c("h"), labels=c("A", "B"))
Fig5ABC <- ggarrange(Fig5AB, Fig5C, ncol=1, align=c("v"), labels=c("", "C"))
Fig5CD <- ggarrange(Fig5C, Fig5D, ncol=1, align=c("v"))
Fig5 <- ggarrange(Fig5AB, Fig5CD, align=c("v"), ncol=1)
Fig5
```
