---
title: 'Mortality analysis including main Figure 2'
author: Cas Swarte
output: html_notebook
# ==========================================================================================
#                       By: Weersma Group, TransplantLines (UMCG)
#
#                       UMCG Transplantlines Project data analysis
# ==========================================================================================
#
# Mortality analysis (Liver Transplant Recipients [LTR], Renal Transplant Recipients [RTR])
#                  This code produces Figure 2 in the main manuscript
#
# ==========================================================================================
#
# NOTE: This is implementation on Mock Data published in this github repo, and is intended 
# for demonstration purposes only, the results are not identical to Figures in the manuscript
#
# NOTE2: Codes are intended to be run from root of this github repo, if running them from 
# different location, make sure to adjust setwd to appropriate location 
# (root of this github repo)
#
# ==========================================================================================
#
# make sure following packages are installed:
# install.packages(c('foreign','tidyverse','ggsignif','survival','rms','survminer'))
#
# ==========================================================================================
---
#Load packages
```{r}
library(foreign)
library(tidyverse)
library(ggsignif)
library(survival)
library(survminer)
library(rms)
```
```{r}
#Figure 2A ordination based on Aitchinson distance
#Load data
#setwd("~TransplantLines-main")
CDmeta <- read.csv("mock_data/Mock_Meta_Final.csv", row.names=1)
CDmeta$ID <- row.names(CDmeta)
CDmeta$ID <- as.character(CDmeta$ID)
CDmeta$ID <- trimws(CDmeta$ID)
rownames(CDmeta) <- CDmeta$ID

centroids_fig2a <- 
  read.csv("deicode_output/species/deicode_taxa_sample_loadings.csv", row.names=1) %>% 
  rownames_to_column("ID") %>% 
  select(ID, PC1, PC2) %>% 
  filter(ID %in% CDmeta[CDmeta$Cross_sectional_samples %in% c("LTR","RTR","Healthy Control"),]$ID) %>%
  left_join(select(CDmeta, ID, Cross_sectional_samples), by="ID") %>%
  mutate(Cross_sectional_samples=factor(Cross_sectional_samples, levels=c("LTR","RTR","Healthy Control"))) %>% 
  group_by(Cross_sectional_samples) %>% 
  summarise(PC1_mean=mean(PC1), PC2_mean=mean(PC2))

Fig2A <- 
  read.csv("deicode_output/species/deicode_taxa_sample_loadings.csv", row.names=1) %>% 
  rownames_to_column("ID") %>% 
  select(ID, PC1, PC2) %>% 
  filter(ID %in% CDmeta[CDmeta$Cross_sectional_samples %in% c("LTR","RTR","Healthy Control"),]$ID) %>%
  left_join(select(CDmeta, ID, Cross_sectional_samples), "ID") %>%
  mutate(Cross_sectional_samples=factor(Cross_sectional_samples, levels=c("LTR","RTR","Healthy Control"))) %>% 
  ggplot(aes(x=PC1, y=PC2, color=Cross_sectional_samples)) +
  geom_point(shape=19, size=3, alpha=0.4) +
  scale_color_manual(values = c("Healthy Control"="darkgray", "RTR"="#45b6fe", "LTR"="#FF7D00"))+
  theme_classic()+ 
  theme(
    axis.title.x = element_text(size=14, face="bold", colour = "black"),
    axis.title.y = element_text(size=14, face="bold", colour = "black"),
    axis.text.x = element_text(size=14, face="bold", colour = "black"),
    axis.text.y = element_text(size=14, face="bold", colour = "black"))+
  theme(legend.text = element_text(face = "bold", size=12),
        legend.title = element_blank(),
        plot.title=element_text(face = "bold",hjust=0.5),
        legend.position="none")+
  geom_point(data=centroids_fig2a, aes(PC1_mean, PC2_mean, fill=Cross_sectional_samples), shape=21, size=6, color="black") +
  scale_fill_manual(values = c("Healthy Control"="darkgray", "RTR"="#45b6fe", "LTR"="#FF7D00"))+
  scale_x_continuous(labels = scales::number_format(accuracy = 0.01, decimal.mark = '.'), breaks=c(-0.06, -0.03, 0.0,0.03, 0.06),limits=c(-0.09, 0.06))+
  scale_y_continuous(labels = scales::number_format(accuracy = 0.01, decimal.mark = '.'), breaks=c(-0.06,-0.03,0.0,0.03,0.06), limits=c(-0.06,0.07))+
  stat_ellipse(type="norm", level=0.75)
Fig2A
```
```{R}
#Figure 2A2 Distance to HC along PC1 and PC2
euclidean_dist_centroids_fig2a <- as.matrix(dist(centroids_fig2a[,c("PC1_mean","PC2_mean")], method="euclidean"))
rownames(euclidean_dist_centroids_fig2a) <- colnames(euclidean_dist_centroids_fig2a) <- c("LTR","RTR","Healthy Control")

Fig2A2 <- data.frame(dist_to_hc=euclidean_dist_centroids_fig2a[3,1:3]) %>% 
  rownames_to_column("group") %>% 
  mutate(group=factor(group, levels=c("LTR","RTR","Healthy Control"))) %>% 
  mutate(dist_to_hc_norm=dist_to_hc/max(dist_to_hc),
         X=1) %>% 
  ggplot(aes(y=dist_to_hc_norm, x=X)) +
  coord_flip() +
  geom_vline(xintercept=1) +
  geom_point(size=8, aes(color=group)) +
  theme(
    axis.title.x = element_text(size=14, face="bold", colour = "black"),
    axis.title.y = element_text(size=14, face="bold", colour = "black"),
    axis.text.x = element_text(size=14, face="bold", colour = "black", angle=45, hjust=1),
    axis.text.y = element_blank())+
  theme(legend.text = element_text(face = "bold", size=12),
        plot.title=element_text(size=14, face="bold", colour = "black", hjust=0.5),
        legend.position="none",
        panel.grid.major=element_blank(), 
        panel.grid.minor=element_blank(), 
        panel.background=element_rect(fill="white"))+
  labs(x=NULL, y="Mean distance to healthy control") +
  scale_colour_manual(values = c("Healthy Control"="darkgray", "RTR"="#45b6fe", "LTR"="#FF7D00"))
Fig2A2
```

```{r}
#Figure 2B Boxplot Diversity LTR, RTR, HC
#subset data
CDmetaBoxplot <- subset(CDmeta, Cross_sectional_samples == "LTR" |Cross_sectional_samples == "RTR" | Cross_sectional_samples == "Healthy Control")

Fig2B <- ggplot(CDmetaBoxplot, aes(x=Cross_sectional_samples, y=Shannon_Species, fill=Cross_sectional_samples)) +
  geom_jitter(aes(color=Cross_sectional_samples), alpha=0.0, width=0.1)+
  geom_boxplot(aes(color=Cross_sectional_samples), alpha=0, width=0.3, size=0.8)+
  theme_classic()+
  theme(
    axis.title.x = element_blank(),    
    axis.title.y = element_text(size=14, face="bold", colour = "black"),
    axis.text.x = element_text(size=14, face="bold", colour = "black"),
    axis.text.y = element_text(size=14, face="bold", colour = "black"),
    plot.title=element_blank())+
  geom_signif(comparisons = list(c("Healthy Control", "RTR"),
                                 c("Healthy Control", "LTR"),
                                 c("RTR", "LTR")),
              textsize=4,
              step_increase = 0.09,
              #P-values are from the original data (Wilcoxon test)
              annotations = c("6.3 x 10-21",
                              "3.1 x 10-9",
                              "0.3"))+
  geom_violin(aes(color = Cross_sectional_samples), trim = FALSE, position = position_dodge(0.9), alpha=0, size=0.8)+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  scale_color_manual(values = c("Healthy Control"="darkgray", "RTR"="#45b6fe", "LTR"="#FF7D00"))+
  scale_y_continuous(labels = scales::number_format(accuracy = 0.1, decimal.mark = '.'), breaks=c(0,1,2,3,4))+
  ylab("Shannon Diversity Index")
Fig2B
```
```{r}
#Figure 2C Kaplan LTR----
#Load data
CDmeta <- read.table("mock_data/MOCK_Meta_Mortality_Cleaned_v2.csv",sep=',',header=T)
CDmeta$ID <- as.character(CDmeta$ID)
CDmeta$ID <- trimws(CDmeta$ID)
rownames(CDmeta) <- CDmeta$ID

CDmetaSurvival_LTR <- subset(CDmeta, Select_samples_mortality  == "LTR")
summary(CDmetaSurvival_LTR$Deceased)
CDmetaSurvival_LTR$DeathNumeric[CDmetaSurvival_LTR$Deceased=="Ja"] = 1
CDmetaSurvival_LTR$DeathNumeric[CDmetaSurvival_LTR$Deceased=="Nee"] = 0
ftable(CDmetaSurvival_LTR$DeathNumeric)

#Split by median (median is from original data
CDmetaSurvival_LTR$new_diversity_group[CDmetaSurvival_LTR$Shannon_Species<=2.481635]="Low diversity"
CDmetaSurvival_LTR$new_diversity_group[CDmetaSurvival_LTR$Shannon_Species>2.481635]="High diversity"
ftable(CDmetaSurvival_LTR$new_diversity)

#Cox Regression Unadjusted
Surv<- coxph(formula = Surv(CDmetaSurvival_LTR$Days_since_sampling, CDmetaSurvival_LTR$DeathNumeric) 
             ~ CDmetaSurvival_LTR$new_diversity_group)
summary(Surv)

#Cox Regression Adjusted
Surv<- coxph(formula = Surv(CDmetaSurvival_LTR$Days_since_sampling, CDmetaSurvival_LTR$DeathNumeric) 
             ~ CDmetaSurvival_LTR$new_diversity_group + 
               CDmetaSurvival_LTR$Months_since_transplantation + 
               CDmetaSurvival_LTR$Age +
               CDmetaSurvival_LTR$Gender)
summary(Surv)

# Model for Plot
fit_post <- survfit(Surv(CDmetaSurvival_LTR$Days_since_sampling, CDmetaSurvival_LTR$DeathNumeric)
                    ~ CDmetaSurvival_LTR$new_diversity_group, data = CDmetaSurvival_LTR)
KM_LTR <- ggsurvplot(
  fit_post,                 
  data = CDmetaSurvival_LTR, 
  break.time.by = 365,  xlim = c(0,1095), 
  ylim = c(0.7, 1),
  legend.labs=c("High Diversity", "Low Diversity"),
  legend.title= "",
  xlab = "Time in days",
  palette = c("darkgray","#FF7D00"),
  ggtheme = theme_classic(base_size=14, base_family = "Arial"),
  font.family = "Arial",
  break.y.by=0.05)
KM_LTR<- ggpar(KM_LTR, 
               font.main = c(14, "bold"),
               font.x = c(14, "bold"),
               font.y = c(14, "bold"),
               font.caption = c(14, "bold"), 
               font.legend = c(14, "bold"),
               font.ytickslab = c(14, "bold", "black"),
               font.xtickslab = c(14, "bold", "black"))
KM_LTR
```
```{r}
#Figure 2F Kaplan RTR----
#Subset data
CDmetaSurvival_RTR <- subset(CDmeta, Select_samples_mortality == "RTR")
CDmetaSurvival_RTR$DeathNumeric[CDmetaSurvival_RTR$Deceased=="Ja"] = 1
CDmetaSurvival_RTR$DeathNumeric[CDmetaSurvival_RTR$Deceased=="Nee"] = 0
ftable(CDmetaSurvival_RTR$DeathNumeric)

#Split by median (median is from original data
CDmetaSurvival_RTR$new_diversity_group[CDmetaSurvival_RTR$Shannon_Species<=2.479713]="Low diversity"
CDmetaSurvival_RTR$new_diversity_group[CDmetaSurvival_RTR$Shannon_Species>2.479713]="High diversity"
ftable(CDmetaSurvival_RTR$new_diversity)

#Cox Regression Unadjusted
Surv<- coxph(formula = Surv(CDmetaSurvival_RTR$Days_since_sampling, CDmetaSurvival_RTR$DeathNumeric) 
             ~ CDmetaSurvival_RTR$new_diversity_group)
summary(Surv)

#Cox Regression Adjusted
CDmetaSurvival_RTR$X<- CDmetaSurvival_RTR$new_diversity_group
Surv<- coxph(formula = Surv(CDmetaSurvival_RTR$Days_since_sampling, CDmetaSurvival_RTR$DeathNumeric) 
             ~ CDmetaSurvival_RTR$new_diversity_group + 
               CDmetaSurvival_RTR$Months_since_transplantation + 
               CDmetaSurvival_RTR$Age +
               CDmetaSurvival_RTR$Gender)
summary(Surv)

# Model for Plot
fit_post <- survfit(Surv(CDmetaSurvival_RTR$Days_since_sampling, CDmetaSurvival_RTR$DeathNumeric)
                    ~ CDmetaSurvival_RTR$new_diversity_group, data = CDmetaSurvival_RTR)
KM_RTR <- ggsurvplot(
  fit_post,                 
  data = CDmetaSurvival_RTR, 
  break.time.by = 365,  xlim = c(0,1825), 
  ylim = c(0.8, 1),
  legend.labs=c("High Diversity", "Low Diversity"),
  legend.title= "",
  xlab = "Time in days",
  palette = c("darkgray","#45b6fe"),
  ggtheme = theme_classic(base_size=14, base_family = "Arial"),
  font.family = "Arial",
  break.y.by=0.05)    
KM_RTR
KM_RTR<- ggpar(KM_RTR, 
               font.main = c(14, "bold"),
               font.x = c(14, "bold"),
               font.y = c(14, "bold"),
               font.caption = c(14, "bold"), 
               font.legend = c(14, "bold"),
               font.ytickslab = c(14, "bold", "black"),
               font.xtickslab = c(14, "bold", "black"))
KM_RTR
```

```{r}
#Figure 2D Spline Shannon LTR----
#Load data
Diss_RCLR <- read.table("mock_data/MockData_Dissimilarities_RCLR.csv",sep=',',header=T)
row.names(Diss_RCLR) <- Diss_RCLR$ID

summary(CDmetaSurvival_LTR$Shannon_Species)
d4 <- CDmetaSurvival_LTR[c("Shannon_Species")]
dd <- datadist(d4, q.display=c(0,1),q.effect=c(0,1))
options(datadist = "dd")

f1<- with(CDmetaSurvival_LTR, cph(Surv(Days_since_sampling,DeathNumeric==1) ~  Shannon_Species))
pdata1 <- Predict(f1, Shannon_Species, ref.zero = TRUE, fun = exp,np = 10000)
range(pdata1$Shannon_Species)
range(CDmetaSurvival_LTR$Shannon_Species)
pdata1 <- Predict(f1, Shannon_Species, ref.zero = F, fun = exp)

#Transform Plot, 1, extract freq per bin, then transform and plot
binFreqTable <- function(x, bins) {
  
  freq = hist(x, breaks=bins, include.lowest=TRUE, plot=FALSE)
  
  ranges = paste(head(freq$breaks,-1), freq$breaks[-1], sep=" - ")
  
  return(data.frame(range = ranges, frequency = freq$counts))
  
}
x<- CDmetaSurvival_LTR$Shannon_Species
FreqDF <- binFreqTable(x,seq(0.42,3.65,by=0.1))
FreqDF$freqtransf <- FreqDF$frequency/10
summary(FreqDF$rangeNum)
FreqDF$rangeNum <- as.numeric(FreqDF$range)
FreqDF$rangeNum <- FreqDF$rangeNum/10
maxY_LTR_Shannon <- 6
maxYforSpline_LTR_Shannon <- max(pdata1$yhat[pdata1$yhat < maxY_LTR_Shannon])

Spline_Shannon_LTR <- ggplot(CDmetaSurvival_LTR, aes(Shannon_Species))+
  geom_bar(aes(x=rangeNum, y=freqtransf), stat="identity", data=FreqDF, color="black", fill="white")+
  geom_ribbon(aes( ymin = pmax(lower,0.00001), ymax = pmin(upper,maxYforSpline_LTR_Shannon)), fill="#FF7D00", color="#FF7D00",alpha = .4, data = as.data.frame(pdata1))+
  geom_line(aes(y = yhat), col = "#FF7D00",alpha = 0.8,linetype=1,size=1.3, data = as.data.frame(pdata1))+
  geom_hline(aes(yintercept = 1), linetype = 2,color="grey",size=1.2,alpha=1)+
  xlab("Shannon Diversity Index") + ylab("Hazard ratio Mortality (95% CI)")+
  theme_classic()+
  scale_x_continuous(limits=c(1.5,3.16),expand = c(0,0), breaks=c(1.5, 2.0, 2.5, 3.0, 3.5))+
  scale_y_continuous(limits=c(0,maxY_LTR_Shannon),expand = c(0,0),
                     sec.axis = sec_axis(trans=~., name="Frequency"))+
  theme(axis.line = element_line(colour = "black"),
        axis.text = element_text(colour = "black", size=14),
        axis.title.x = element_text(color="black", size=14, face="bold", vjust=-0.5),
        axis.title.y.left = element_text(color="black", size=14, face="bold", vjust=4),
        axis.text.x = element_text(size=14, face="bold", colour = "black"),
        axis.text.y = element_text(size=14, face="bold", colour = "black"),
        axis.title.y.right = element_text(color="black", size=14, face="bold", vjust=4),
        plot.title = element_text(face="bold",size=17,hjust = 0.4,vjust=3),plot.margin=unit(c(1.5,0.5,0.5,0.5),"cm"))
Spline_Shannon_LTR
```
```{r}
#Figure 2G Spline Shannon RTR----
summary(CDmetaSurvival_RTR$Shannon_Species)
d4 <- CDmetaSurvival_RTR[c("Shannon_Species")]
dd <- datadist(d4, q.display=c(0,1),q.effect=c(0,1))
options(datadist = "dd")

f1<- with(CDmetaSurvival_RTR, cph(Surv(Days_since_sampling,DeathNumeric==1) ~  Shannon_Species))
pdata1 <- Predict(f1, Shannon_Species, ref.zero = TRUE, fun = exp,np = 10000)
range(pdata1$Shannon_Species)
range(CDmetaSurvival_RTR$Shannon_Species)
pdata1 <- Predict(f1, Shannon_Species, ref.zero = F, fun = exp)

#Transform Plot, 1, extract freq per bin, then transform and plot
binFreqTable <- function(x, bins) {
  
  freq = hist(x, breaks=bins, include.lowest=TRUE, plot=FALSE)
  
  ranges = paste(head(freq$breaks,-1), freq$breaks[-1], sep=" - ")
  
  return(data.frame(range = ranges, frequency = freq$counts))
  
}
x<- CDmetaSurvival_RTR$Shannon_Species
FreqDF <- binFreqTable(x,seq(0.50,3.7,by=0.1))
FreqDF$freqtransf <- FreqDF$frequency/10
summary(FreqDF$rangeNum)
FreqDF$rangeNum <- as.numeric(FreqDF$range)
FreqDF$rangeNum <- FreqDF$rangeNum/10

maxY_Shannon_RTR <- 8
maxYforSpline_Shannon_RTR <- max(pdata1$yhat[pdata1$yhat < maxY_Shannon_RTR])

Spline_Shannon_RTR <- ggplot(CDmetaSurvival_RTR, aes(Shannon_Species))+
  geom_bar(aes(x=rangeNum, y=freqtransf), stat="identity", data=FreqDF, color="black", fill="white")+
  geom_ribbon(aes( ymin = lower, ymax = upper), fill="#45b6fe", color="#45b6fe",alpha = .4, data = as.data.frame(pdata1))+
  geom_line(aes(y = yhat), col = "#45b6fe",alpha = 0.8,linetype=1,size=1.3, data = as.data.frame(pdata1))+
  geom_hline(aes(yintercept = 1), linetype = 2,color="grey",size=1.2,alpha=1)+
  xlab("Shannon Diversity Index") + ylab("Hazard ratio Mortality (95% CI)")+
  theme_classic()+
  scale_x_continuous(limits=c(1.5,3.16),expand = c(0,0), breaks=c(1.5, 2.0, 2.5, 3.0, 3.5))+
  scale_y_continuous(limits=c(0,maxY_Shannon_RTR),expand = c(0,0), breaks=c(0,1,2,3,4,5,6,7,8),
                     sec.axis = sec_axis(trans=~., name="Frequency", breaks=c(0,1,2,3,4,5,6,7,8)))+
  theme(axis.line = element_line(colour = "black"),
        axis.text = element_text(colour = "black", size=14),
        axis.title.x = element_text(color="black", size=14, face="bold", vjust=-0.5),
        axis.title.y.left = element_text(color="black", size=14, face="bold", vjust=4),
        axis.text.x = element_text(size=14, face="bold", colour = "black"),
        axis.text.y = element_text(size=14, face="bold", colour = "black"),
        axis.title.y.right = element_text(color="black", size=14, face="bold", vjust=4),
        plot.title = element_text(face="bold",size=17,hjust = 0.4,vjust=3),plot.margin=unit(c(1.5,0.5,0.5,0.5),"cm"))
Spline_Shannon_RTR
```
```{r}
#Figure 2E Spline Aitchison distance to HC LTR----
MortalityDissimilarity<- merge(CDmetaSurvival_LTR, Diss_RCLR, by="row.names")

#Cox Regression Unadjusted
Surv<- coxph(formula = Surv(MortalityDissimilarity$Days_since_sampling, MortalityDissimilarity$DeathNumeric) 
             ~ scale(MortalityDissimilarity$DToHC))
summary(Surv)

#Cox Regression Adjusted
Surv<- coxph(formula = Surv(MortalityDissimilarity$Days_since_sampling, MortalityDissimilarity$DeathNumeric) 
             ~ scale(MortalityDissimilarity$DToHC) + 
               MortalityDissimilarity$Months_since_transplantation + 
               MortalityDissimilarity$Age +
               MortalityDissimilarity$Gender)
summary(Surv)

summary(MortalityDissimilarity$DToHC)
d4 <- MortalityDissimilarity[c("DToHC")]
dd <- datadist(d4, q.display=c(0,1),q.effect=c(0,1))
options(datadist = "dd")
f1<- with(MortalityDissimilarity, cph(Surv(Days_since_sampling,DeathNumeric==1) ~  DToHC))
pdata1 <- Predict(f1, DToHC, ref.zero = TRUE, fun = exp,np = 10000)


#Transform Plot, 1, extract freq per bin, then transform and plot
binFreqTable <- function(x, bins) {
  
  freq = hist(x, breaks=bins, include.lowest=TRUE, plot=FALSE)
  
  ranges = paste(head(freq$breaks,-1), freq$breaks[-1], sep=" - ")
  
  return(data.frame(range = ranges, frequency = freq$counts))
  
}
x<- MortalityDissimilarity$DToHC
FreqDF <- binFreqTable(x,seq(0,1,by=0.01))
FreqDF$freqtransf <- FreqDF$frequency/10
FreqDF$rangeNum <- as.numeric(FreqDF$range)
FreqDF$rangeNum <- FreqDF$rangeNum/100
maxY_LTR_DTHC <- 6
maxYforSpline_LTR_DTHC<- max(pdata1$yhat[pdata1$yhat < maxY_LTR_DTHC])

Spline_DTHC_RCLR_LTR <- ggplot(MortalityDissimilarity, aes(DToHC))+
  geom_bar(aes(x=rangeNum, y=freqtransf), stat="identity", data=FreqDF, color="black", fill="white")+
  geom_ribbon(aes( ymin = pmax(lower,0.00001), ymax = pmin(upper,maxYforSpline_LTR_DTHC)), fill="#FF7D00", color="#FF7D00",alpha = .4, data = as.data.frame(pdata1))+
  geom_line(aes(y = yhat), col = "#FF7D00",alpha = 0.8,linetype=1,size=1.3, data = as.data.frame(pdata1))+
  geom_hline(aes(yintercept = 1), linetype = 2,color="grey",size=1.2,alpha=1)+
  xlab("Aitchison distance to healthy controls") + ylab("Hazard ratio Mortality (95% CI)")+
  theme_classic()+
  scale_x_continuous(limits=c(0.2,0.4),expand = c(0,0))+
  scale_y_continuous(limits=c(0,maxY_LTR_DTHC),expand = c(0,0),
                     sec.axis = sec_axis(trans=~., name="Frequency", breaks=c(0,1,2,3,4,5,6,7,8)))+
  theme(axis.line = element_line(colour = "black"),
        axis.text = element_text(colour = "black", size=14),
        axis.title.x = element_text(color="black", size=14, face="bold", vjust=-0.5),
        axis.title.y.left = element_text(color="black", size=14, face="bold", vjust=4),
        axis.text.x = element_text(size=14, face="bold", colour = "black"),
        axis.text.y = element_text(size=14, face="bold", colour = "black"),
        axis.title.y.right = element_text(color="black", size=14, face="bold", vjust=4),
        plot.title = element_text(face="bold",size=17,hjust = 0.4,vjust=3),plot.margin=unit(c(1.5,0.5,0.5,0.5),"cm"))
Spline_DTHC_RCLR_LTR
```
```{r}
#Figure 2H Spline Distance to HC RTR----
MortalityDissimilarity<- merge(CDmetaSurvival_RTR, Diss_RCLR, by="row.names")

#Cox Regression Unadjusted
Surv<- coxph(formula = Surv(MortalityDissimilarity$Days_since_sampling, MortalityDissimilarity$DeathNumeric) 
             ~ scale(MortalityDissimilarity$DToHC))
summary(Surv)

#Cox Regression Unadjusted
Surv<- coxph(formula = Surv(MortalityDissimilarity$Days_since_sampling, MortalityDissimilarity$DeathNumeric) 
             ~ scale(MortalityDissimilarity$DToHC) + 
               MortalityDissimilarity$Months_since_transplantation + 
               MortalityDissimilarity$Age +
               MortalityDissimilarity$Gender)
summary(Surv)

summary(MortalityDissimilarity$DToHC)
d4 <- MortalityDissimilarity[c("DToHC")]
dd <- datadist(d4, q.display=c(0,1),q.effect=c(0,1))
options(datadist = "dd")
f1<- with(MortalityDissimilarity, cph(Surv(Days_since_sampling,DeathNumeric==1) ~  DToHC))
pdata1 <- Predict(f1, DToHC, ref.zero = TRUE, fun = exp,np = 10000)

#Transform Plot, 1, extract freq per bin, then transform and plot
binFreqTable <- function(x, bins) {
  
  freq = hist(x, breaks=bins, include.lowest=TRUE, plot=FALSE)
  
  ranges = paste(head(freq$breaks,-1), freq$breaks[-1], sep=" - ")
  
  return(data.frame(range = ranges, frequency = freq$counts))
  
}
x<- MortalityDissimilarity$DToHC
FreqDF <- binFreqTable(x,seq(0,1,by=0.01))
FreqDF$freqtransf <- FreqDF$frequency/10
FreqDF$rangeNum <- as.numeric(FreqDF$range)
FreqDF$rangeNum <- FreqDF$rangeNum/100

maxY_DTHC_RTR  <- 8
maxYforSpline_DTHC_RTR <- max(pdata1$yhat[pdata1$yhat < maxY_DTHC_RTR])

Spline_DTHC_RCLR_RTR <- ggplot(MortalityDissimilarity, aes(DToHC))+
  geom_bar(aes(x=rangeNum, y=freqtransf), stat="identity", data=FreqDF, color="black", fill="white")+
  geom_ribbon(aes( ymin = pmax(lower,0.00001), ymax = pmin(upper,maxYforSpline_DTHC_RTR)), fill="#45b6fe", color="#45b6fe",alpha = .4, data = as.data.frame(pdata1))+
  geom_line(aes(y = yhat), col = "#45b6fe",alpha = 0.8,linetype=1,size=1.3, data = as.data.frame(pdata1))+
  geom_hline(aes(yintercept = 1), linetype = 2,color="grey",size=1.2,alpha=1)+
  xlab("Aitchison distance to healthy controls") + ylab("Hazard ratio Mortality (95% CI)")+
  theme_classic()+
  scale_x_continuous(limits=c(0.2,0.4),expand = c(0,0))+
  scale_y_continuous(limits=c(0,maxY_DTHC_RTR),expand = c(0,0),
                     sec.axis = sec_axis(trans=~., name="Frequency", breaks=c(0,1,2,3,4,5,6,7,8)))+
  theme(axis.line = element_line(colour = "black"),
        axis.text = element_text(colour = "black", size=14),
        axis.title.x = element_text(color="black", size=14, face="bold", vjust=-0.5),
        axis.title.y.left = element_text(color="black", size=14, face="bold", vjust=4),
        axis.text.x = element_text(size=14, face="bold", colour = "black"),
        axis.text.y = element_text(size=14, face="bold", colour = "black"),
        axis.title.y.right = element_text(color="black", size=14, face="bold", vjust=4),
        plot.title = element_text(face="bold",size=17,hjust = 0.4,vjust=3),plot.margin=unit(c(1.5,0.5,0.5,0.5),"cm"))
Spline_DTHC_RCLR_RTR
```
```{r}
#Figure 2  Arrange all panels----
Fig2AB <- ggarrange(Fig2A, Fig2B, nrow=1, align=c("h"), labels = c("A", "B"))
Fig2CDE <- ggarrange(KM_LTR$plot, Spline_Shannon_LTR, Spline_DTHC_RCLR_LTR, nrow=1, align=c("h"), labels=c("C","D","E"))
Fig2FGB <- ggarrange(KM_RTR$plot, Spline_Shannon_RTR, Spline_DTHC_RCLR_RTR, nrow=1, align=c("h"), labels=c("F","G","H"))
FinalFig2 <- ggarrange(Fig2AB, Fig2CDE, Fig2FGB, ncol=1, align=c("v"))
FinalFig2
```
